### PR TITLE
MISP Authentication with Open ID Connect / OAuth2

### PR DESCRIPTION
**Pull request by garrit-schroeder**
## Generic requirements in order to contribute to MISP:

* One Pull Request per fix/feature/change/...
* Keep the amount of commits per PR as small as possible: if for any reason, you need to fix your commit after the pull request, please squash the changes in one single commit (or tell us why not)
* Always make sure it is mergeable in the default branch (as of today 2020-05-05: branch 2.4)
* Please make sure Travis CI works on this request, or update the test cases if needed
* Any major changes adding a functionality should be disabled by default in the config

#### What does it do?

This pull request allows users to sign in with a configured identity provider using the protocol open id connect / oauth2.
Mostly used the code of Pull Request https://github.com/MISP/MISP/pull/6661 Azure AD Authentication.
Tested with Keycloak v11

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by JakubOnderka** [comment]
Hello, I have bad and good news for you: support for OpenID Connect authentication was merged into MIPS 4 days ago: https://github.com/MISP/MISP/pull/6984

**Comment by garrit-schroeder** [comment]
Haha well. That's good. Going to try that out soon. Will this be available in the next update?

**Comment by adulau** [comment]
Yes it will be available in the next release. Thanks again for your pull-request.

**Comment by garrit-schroeder** [comment]
@JakubOnderka Could you please help me out to setup oidc with your code. I am having struggle to get this working. 
I get directed to my IDP (Keycloak) that works fine but then I end up in a redirect loop until my browser stops because of too many redirects. 

I debug the code and within the library of Jumbojett 
The following if clause is never run through (even though i can see in my browser that it has an attribute in the url ?....&code=XXX)

File: OpenIDConnectClient.php Line 297

```
// If we have an authorization code then proceed to request a token
if (isset($_REQUEST['code'])) {

    $code = $_REQUEST['code'];
    $token_json = $this->requestTokens($code);
```
Your help is much appreciated

**Comment by JakubOnderka** [comment]
OIDC login is supported in 2.4.140.

**Pull request closed without merging**
