### PR TITLE
Improve contributing.md, Add coding style, workflow

### PR DESCRIPTION
**Pull request by enjeck**
#### What does it do?

* Adds more content to the contributing guide
* Add a coding style guide. 
* Add a file detailing how we use GitHub

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by enjeck** [comment]
Some tests have failed here, but I can't find what's wrong :/

**Review by adulau — COMMENTED** [review]
What's the reference to briarproject.org regarding labels?

**Comment by adulau** [comment]
I saw references to another code conduct but we have already one https://github.com/MISP/MISP/blob/2.4/code_of_conduct.md

**Comment by enjeck** [comment]
> What's the reference to briarproject.org regarding labels?

@adulau Damn. My bad. I had written something similar for Briar Project as well, and I got a bit confused

**Comment by enjeck** [comment]
@adulau Fixed :)

**Comment by adulau** [comment]
Thank you very much.

**Pull request merged**
