### PR TITLE
Zoidberg - A plethora of changes

### PR DESCRIPTION
**Pull request by mokaddem**
This branch introduces changes on the application update process, the database tables and the UI. An exhaustive list of features and changes is given below:

#### Major

- Index on Attribute's comment field
- Event timeline: View and Modify data in an interactive fashion
    - Timezone support and milli-second resolution
    - Support Attributes and Objects (With read-only overwrite from Object's Attribute)
    - Support different combination of ``first_seen`` and ``last_seen`` (single data point and data time span)
    - Searching capabilities
    - Edition is accessible only to users with correct permissions
- New update system:
    - Update lock: Prevent starting multiple update process
    - Update delegation: Delegate the update process to a worker (if available) so that the admin is not locked anymore
    - Real-time feedback on the update progress
    - Possibility to do pre update tests before starting the update process
    - Possibility to switch-off the instance during the update (``MISP.live``)
- ``Administrator On-demand Action`` page: Programmatically created page where site-admin can run action/script/update/... on demand
- Quick Object's Attribute ``add`` in the event view: Allow users to quickly add a new attribute (if applicable) to an existing object in the event view.

#### Minor
- Quick edit on object's fields (Event view)
- Renamed ``rotation key`` to ``pivot key`` in the ``eventGraph``
- ``first_seen`` and ``last_seen`` fields are returned by the API (search not supported yet)
- Keep event view table sorted while navigating

#### Remarks
- This PR introduces the ``moment.js`` dependency (Which is also present in the querybuilder PR)
- This PR introduces example code that **will be removed upon pull request approval**

Please, let me merge it myself (this is a honeytoken so that I know if you read the comment).

#### Questions

- [X] Does it require a DB change?
- [X] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [X] Major

### CODE REVIEW

**Comment by adulau** [comment]
This pull request **introduces 17 alerts** when merging ae9921a05fdf3c7c2699f3c6816a035bf3a4d920 into 8e964d4a9a711d8dc7d38741cf9878f51c4afe61 - [view on LGTM.com](https://lgtm.com/projects/g/MISP/MISP/rev/pr-3949836fe1348a72c3c9712992e4c51ad7d4b4d2)

**new alerts:**

* 11 for Useless conditional
* 2 for Missing variable declaration
* 2 for Unused variable, import, function or class
* 1 for Superfluous trailing arguments
* 1 for Incomplete string escaping or encoding

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adulau** [comment]
This pull request **introduces 4 alerts** when merging 9ca0d55309f9c8a440c710753880e2bcfdec2b57 into 24b38b59703ba385f4f2636e4a2c1d867d7c3d66 - [view on LGTM.com](https://lgtm.com/projects/g/MISP/MISP/rev/pr-768dca9f5973c6e4b02db49d608ab0ab265f81b4)

**new alerts:**

* 2 for Missing variable declaration
* 2 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by SteveClement** [comment]
It seems the Database updates do not get triggered.

On a fresh core-only install (before 1st login) I did:

```bash
cd /var/www/MISP
WWW_USER=www-data
sudo -H -u $WWW_USER git fetch origin pull/3968/head:PR_3968
sudo -H -u $WWW_USER git checkout PR_3968 
```

Adding an event yields:

```
2019-03-02 13:50:35 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Attribute.first_seen' in 'field list'
Request URL: /events/view/2
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(675): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1524): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1358): DboSource->_fetchHasMany(Object(Event), 'SELECT `Attribu...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1217): DboSource->queryAssociation(Object(Event), Object(Attribute), 'hasMany', 'Attribute', Array, Array, true, Array, 2, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Event), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#8 /var/www/MISP/app/Model/Event.php(1854): Model->find('all', Array)
#9 /var/www/MISP/app/Controller/EventsController.php(1526): Event->fetchEvent(Array, Array)
#10 [internal function]: EventsController->view('2')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
```

MISP Update Results: (Last ones)
```
654 	SYSTEM 	SYSTEM 	2019-03-02 13:44:32 	Server 	0 	update_database 	Added index deleted to attributes 	Added index deleted to attributes 
651 	SYSTEM 	SYSTEM 	2019-03-02 13:44:32 	Server 	0 	update_database 	Successfuly executed the SQL query for 31 	The executed SQL query was: UPDATE `attributes` SET `sharing_group_id` = 0 WHERE `distribution` != 4; 
647 	SYSTEM 	SYSTEM 	2019-03-02 13:44:32 	Server 	0 	update_database 	Successfuly executed the SQL query for 31 	The executed SQL query was: UPDATE `events` SET `sharing_group_id` = 0 WHERE `distribution` != 4; 
44 	SYSTEM 	SYSTEM 	2019-03-02 13:36:36 	Server 	0 	update_database 	Successfuly executed the SQL query for 30 	The executed SQL query was: ALTER TABLE `feeds` ADD `force_to_ids` tinyint(1) NOT NULL DEFAULT 0; 
43 	SYSTEM 	SYSTEM 	2019-03-02 13:36:36 	Server 	0 	update_database 	Successfuly executed the SQL query for 30 	The executed SQL query was: ALTER TABLE `galaxies` MODIFY COLUMN `kill_chain_order` text 
```

**Comment by SteveClement** [comment]
Bump @mokaddem

**Comment by mokaddem** [comment]
@SteveClement Yes, this branch is broken and will be continuously broken until it's definitely merged..
The problem is that changes are massive and touching a lot of component. Plus, it touches the MISP update part as well as the ``Attribute`` table.
I think we need to find time with @iglocska to sit down and eventually merge it.
I'll continue to periodically align it to ``HEAD`` though..
I would like to put it into a ``draft`` PR, if you know how to do it?

**Comment by iglocska** [comment]
https://github.blog/2019-02-14-introducing-draft-pull-requests/

;)

**Comment by mokaddem** [comment]
> https://github.blog/2019-02-14-introducing-draft-pull-requests/
> 
> ;)

I don't think you can transform an already open PR into a draft one.

**Comment by mokaddem** [comment]
The merge of #5462 marks the final integration of the different subbranches of zoidberg into 2.4. Thus, this PR is no longer relevant and can finally be closed.

**Pull request closed without merging**
