### PR TITLE
Custom warninglists

### LINKED ISSUE #7434: Feature request: Warninglist categories
**Is your feature request related to a problem? Please describe.**
Warninglist currently mix different categories of list. 
* First category is 100 % sure invalid IoC, like internal IP range or hash of empty file
* Second category is most probably false positive, like communication to public DNS server or Windows Update IP.
* Third category is know indicator, like IP address that belongs to public cloud.

**Describe the solution you'd like**
Every warninglist will belongs to one of category. When viewing event, *Warning: Potential false positives* box will change color and description according to highest warninglist category. Also this information will be available thought API.

### PR DESCRIPTION
**Pull request by JakubOnderka**
#### What does it do?

Fixes #7434 and part of #7210.

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by iglocska** [comment]
Just played with it a bit, looks good, but there are a few things that we'd need to change before merging: 

1. The DB version needs to be bumped before we merge
2. The DB update script needs to kick the user out (=> true) otherwise we get notice errors until logout
3. The categories are confusing, I myself have no idea what the other two categories are meant to do. We've had some discussions on the proposed categories in a prior discussion (block, warn and something else that I can't recall) where the idea would be that we separate out warninglists that are meant to be used in the automation and ones that are purely meant to warn the users. I'll try to find the discussion back.
4. No edit button on the index

**Comment by JakubOnderka** [comment]
> The DB version needs to be bumped before we merge

Fixed.

> The DB update script needs to kick the user out (=> true) otherwise we get notice errors until logout

Fixed.

> No edit button on the index

There should be edit icon for custom warninglist.

> The categories are confusing

Yes, that possible. My idea was:
* Invalid identifier - IoC that is 100 % sure that is invalid, like private IP address, hash of empty or EICAR file
* False positive - known good, like known DNS servers, Windows Update or Wikipedia IP addresses or domains
* Known identifier - something that is just on the list, but it doesn't mean that it is false positive, like public cloud providers or Top 1000 domains etc.

I will be happy if you propose better names or maybe even new category, or we can merge first two categories into *False positive*.

**Comment by iglocska** [comment]
Ah I see, so you would differentiate between the certainty of those two. The problem is that invalid identifier is in the eye of the beholder - on a shared community my own infrastructure is ground truth to me in being 100% not something I want to detect / block on, but if I have a compromise others in the community might disagree. So what I'd do: Merge those two simply have a false positive + an informational/purely warning list (false positive and known identifier are fine for the naming).

Later on we should change the behaviour of enforceWarninglist to accept, in addition to the boolean values, a list of warninglist IDs, that way we can selectively enforce lists that are of our own infrastructure if we wish not to use the false positive lists.

**Comment by JakubOnderka** [comment]
Changed, not there are just two categories:
* False positive
* Known identifier

**Pull request merged**
