### PR TITLE
add referer type

### PR DESCRIPTION
**Pull request by truckydev**
https://github.com/MISP/MISP/issues/2359

## Generic requirements in order to contribute to MISP:

* One Pull Request per fix/feature/change/...
* Keep the amount of commits per PR as small as possible: if for any reason, you need to fix your commit after the pull request, please squash the changes in one single commit (or tell us why not)
* Always make sure it is mergeable in the default branch (as of today 2016-06-03: branch 2.4)
* Please make sure Travis CI works on this request, or update the test cases if needed
* Any major changes adding a functionality should be disabled by default in the config

#### What does it do?

If it fixes an existing issue, please use github syntax: `#<IssueID>`

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by adulau** [comment]
Interesting but we could create a generic MISP http header object template where referer or other could fit. I'll look it.

**Comment by truckydev** [comment]
refere is in http-request object
https://github.com/MISP/misp-objects/blob/master/objects/http-request/definition.json#L63

I hope misp-object come soon :)
but in json "misp-attribute": "other"

maybe change by referer after this PR no ?

**Comment by adulau** [comment]
currently the misp attribute should match an existing one. `other` was the most appropriate.

**Comment by adulau** [comment]
I suppose we can close this PR as misp-objects are implemented and a complete HTTP object template exists in https://github.com/MISP/misp-objects/blob/master/objects/http-request/definition.json. @truckydev let me know if there is any issue with the object. Thank you.

**Pull request closed without merging**
