### PR TITLE
Show proper number of attributes and events for tags

### PR DESCRIPTION
**Pull request by JakubOnderka**
#### What does it do?

Before that change, no ACL was applied, so MISP shows incorrect numbers.

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by iglocska** [comment]
I think this was one of those cases where we said we'd be fine ignoring the ACL due to the potential performance hurdles this would lead to. Are you seeing a substantial increase in query times with this applied?

**Comment by JakubOnderka** [comment]
> I think this was one of those cases where we said we'd be fine ignoring the ACL due to the potential performance hurdles this would lead to. Are you seeing a substantial increase in query times with this applied?

Good point. I just test it on my testing instance and it looks good (but I didn't measure it), but I will check it in larger instance and measure the difference.

**Comment by JakubOnderka** [comment]
> > I think this was one of those cases where we said we'd be fine ignoring the ACL due to the potential performance hurdles this would lead to. Are you seeing a substantial increase in query times with this applied?
> 
> Good point. I just test it on my testing instance and it looks good (but I didn't measure it), but I will check it in larger instance and measure the difference.

I just tested it and fix one problem (SQL query was send even if tag doesn't contains any attribute or event). Showing page with 50 tags takes on my big instance 670 ms instead of 650 ms before.

**Comment by iglocska** [comment]
That sounds like an acceptable loss, let's give it a whirl! Thanks a lot!

**Comment by iglocska** [comment]
Sorry reverted it for now. It is causing ~140GB of memory usage for some users... :)

**Pull request merged**
