### PR TITLE
Dashboard widgets

### PR DESCRIPTION
**Pull request by cudeso**
- Widget to display system resources (df, cpu, mem)
- Widget to display the latest sightings
- Widget to display the false positive sightings above certain treshold

#### What does it do?

Additional dashboard widgets

#### Questions

- [ ] Does it require a DB change? No 
- [ ] Are you using it in production? Yes
- [ ] Does it require a change in the API (PyMISP for example)? No

### CODE REVIEW

**Comment by adulau** [comment]
Thanks a lot. Could you review the codacy notification? 

https://app.codacy.com/manual/MISP/MISP/pullRequest?prid=5651917

Thanks and enjoy your day.

**Comment by iglocska** [comment]
Awesome stuff!

**Comment by cudeso** [comment]
@adulau  : changed unneeded else clause and removed some optional variables ; but some of the other codacy notification don't seem relevant (Avoid using static access to class 'ClassRegistry' and use of file_get_contents <- don't see another way of getting system memory, other than introducing a lot of extra complexity ;-) )
> Thanks a lot. Could you review the codacy notification?

**Comment by adulau** [comment]
Thanks a lot. This is a great contribution!

**Pull request merged**
