### PR TITLE
Related event ui

### PR DESCRIPTION
**Pull request by mokaddem**
- Added collapse support for related events in feeds and servers
- New layout ``Element`` for related events

This is what ``Related Events`` will look like. It takes more space (100% more vertically), but provide more contextual data than before (Event ``info``, ``orgc`` and unique ``correlation count``).
image

Related to #4148

### CODE REVIEW

**Comment by iglocska** [comment]
As always, I approve of this GraphMan improvement!

**Comment by mokaddem** [comment]
Will continue the integration then! :)

**Comment by mokaddem** [comment]
Pull request ready for review.
A typically ``23:59``

**Comment by iglocska** [comment]
Thanks a lot!

**Pull request merged**
