### PR TITLE
WIP - Make MISP Sexy Again!

### PR DESCRIPTION
**Pull request by rhaist**
This is a work in progress (WIP) pull request to show my ongoing work to:
- update Twitter Boostrap to current 3.x (if this takes some time maybe even 4.x)
- make MISP frontend responsive to be displayed on devices that don't like fixed-width CSS
- remove legacy / not needed CSS code
- remove legacy / not needed JS code
- remove box-shadows, glass look, round cornering all over the place
- document template code

This is nowhere near a usable, finished state. I just want to keep other developers informed regarding other design decisions. I will provide a showcase web-server when most UI features are ported.

### CODE REVIEW

**Comment by adulau** [comment]
Thank you very much for the ongoing work on this. Just a small thing, maybe it would be nicer to have a download/updater script for the fonts and the Twitter Bootstrap to avoid the have the files directly in the MISP repository.

**Comment by rhaist** [comment]
@adulau good idea. As a lot of people need to use MISP in an air-gapped environment I moved dependency installation to the already present Makefile.

So people can pull the dependencies on a internet host and just copy it over.
I assumed bower or grunt is no option here :)

**Comment by rhaist** [comment]
Due to constant (understandable) maintenance and feature changes from your side it is very hard to keep my extensive template code changes merged with upstream.

I don't see a way to do this effort in one single merge and will try to split this in some smaller PRs that do not break the status-quo for a start.

**Comment by Rafiot** [comment]
yes, this is probably the best way to do it, small incremental upgrades :)

**Comment by Rafiot** [comment]
@SleuthKid any chance you can allocate a bit of time on that? (especially the small incremental upgrades :) )

**Comment by rhaist** [comment]
Will be devided in small - non breaking changes.

**Pull request closed without merging**
