### PR TITLE
French translation achieved

### PR DESCRIPTION
**Pull request by ater49**
#### What does it do?

Finalization of French translation for MISP

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [ ] Major
- [X] Minor
- [ ] Patch

### CODE REVIEW

**Comment by adulau** [comment]
@SteveClement @ater49 could you check the conflicting parts? Thanks a lot.

**Comment by adulau** [comment]
@SteveClement Could you have a look? as we will release a new very version soon(tm) ;-)

**Comment by ater49** [comment]
@adulau @SteveClement already pushed french translation monday, so I can close this PR, is it okay?

**Comment by SteveClement** [comment]
@ater49 I indeed pushed this already :)

Feel free to test if it visually works fine.

Thanks for the great contrib.

**Pull request closed without merging**
