### PR TITLE
save what is edited for pubsub module

### PR DESCRIPTION
**Pull request by truckydev**
This PR  come with https://github.com/MISP/MISP/pull/3157 :)
#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by iglocska** [comment]
This may not be the best approach to signaling what has changed for the pubsub channel - keep in mind, if you go through the attribute edit function this will work - if you go through any of the other functionalities that could edit an attribute (such as event edit, sync, feed pull, etc) - it will not. A much better approach would be to do this on a model beforesave level for example.

**Comment by truckydev** [comment]
that's exactly what I wanted to do at first but I didn't know how to get back what was changing during the modification. 
If I make something like that in the model.beforeSave : 
```php
CakeLog::write('debug', print_r($this->data, true));
```

That's why, I added this information in the controller, and next update what go to the pubsub
https://github.com/MISP/MISP/pull/3157/files#diff-cd568c0d060e48659582fb1bc5f06d5bR621

Next,  was not clear about the purpose : It is for this PR : 
https://github.com/MISP/misp-modules/pull/178

If I don't have this information, I can not update the hashstore : 
https://github.com/MISP/misp-modules/pull/178/files#diff-298f77667c2e74d0e60844b5baece509R57

I try another way latter, but if you have any idea what approach I'm taking.

**Comment by truckydev** [comment]
Ok,
Thinking about it for two seconds is actually pretty easy, lol.
I have updated the PR to take into account your remark.
https://github.com/MISP/MISP/pull/3157/files

I think you can close this one ^^

**Comment by truckydev** [comment]
cf https://github.com/MISP/MISP/pull/3157

**Pull request closed without merging**
