### PR TITLE
open tags search on attribute with api

### PR DESCRIPTION
**Pull request by truckydev**
https://github.com/MISP/MISP/issues/1870

how to use : 
```python
import requests
session = requests.Session()
session.headers.update(
                {'Authorization': 'HHHhhh22GGGGGGggggggg2222222222',
                 'Accept': 'application/json',
                 'content-type': 'application/json'})
postData = {'attributeTags':
        ['question:univers="loading"', 'answer:univers="42"']
        }
url = 'http://misp.local/attributes/restSearch/json'
r = session.post(url, data=json.dumps(postData))
print(r.text)
```

sample result : 
```json
{
    "response": {
        "Attribute": [
            {
                "type": "ip-dst",
                "category": "Network activity",
                "uuid": "57723088-74c8-4a50-91db-4010950d0000",
                "to_ids": true,
                "deleted": false,
                "value": "42.42.42.42",
                "event_id": "2",
                "comment": "So long, and thanks for all the fish",
                "sharing_group_id": "0",
                "distribution": "0",
                "id": "42",
                "timestamp": "-883620000",
                "disable_correlation": false
            }
        ]
    }
}
```

#### What does it do?

If it fixes an existing issue, please use github syntax: `#1870`

#### Questions

- [ ] Does it require a DB change?
- [x] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by iglocska** [comment]
Just checked the PR, there was a misunderstanding, could you change the API so that tag search happens when attributeTags is passed as a parameter? 

So the payload should be:

/attributes/restSearch/json

{"attributeTags":["tag1", "tag2"]}

instead of the current:

{"tags":["tag1", "tag2"]}

**Comment by truckydev** [comment]
Ho ok I do this quick

**Comment by truckydev** [comment]
it's work but not with pymisp now

**Comment by truckydev** [comment]
Add PR in PyMISP ^^
https://github.com/MISP/PyMISP/pull/124

**Comment by truckydev** [comment]
Ok fixe with : https://github.com/MISP/MISP/commit/6cdb8479cbbb3cfa7f6a0790996857f78fd247f2

**Pull request closed without merging**
