### PR TITLE
Banco do Brasil public feed

### PR DESCRIPTION
**Pull request by threatintelBB**
Added Banco do Brasil public feed

### CODE REVIEW

**Comment by iglocska** [comment]
Thanks a lot!

**Comment by iglocska** [comment]
Hmm, looks like the feed is unavailable, could you double check the URL?

**Comment by cgoncalves1** [comment]
> Hmm, looks like the feed is unavailable, could you double check the URL?

Hello I'm from Banco do Brasil's CTI team. The URL is correct. Maybe there is a firewall rule blocking access, we'll check it out.

**Comment by threatintelBB** [comment]
Hello, the feed URL is now available. Thanks!!!

**Pull request merged**
