### PR TITLE
not local and no uuid, it's an invalid organisation

### PR DESCRIPTION
**Pull request by sfossen**
## Generic requirements in order to contribute to MISP:
- One Pull Request per fix/feature/change/...
- Keep the amount of commits per PR as small as possible: if for any reason, you need to fix your commit after the pull request, please squash the changes in one single commit (or tell us why not)
- Always make sure it is mergeable in the default branch (as of today 2016-06-03: branch 2.4)
- Please make sure Travis CI works on this request, or update the test cases if needed
- Any major changes adding a functionality should be disabled by default in the config
#### What does it do?

If it fixes an existing issue, please use github syntax: `#<IssueID>`
#### Questions
- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?
#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

sync fails with
[2016-06-01 21:04:26] main.ERROR: {"queue":"default","id":"99b7d5ef61e24389ea2edf8c3f209856","class":"ServerShell","args":[["pull","1","1","full","2075"]]} failed: SQLSTATE[HY000]: General error: 1364 Field 'uuid' doesn't have a default value {"type":"fail","log":"SQLSTATE[HY000]: General error: 1364 Field 'uuid' doesn't have a default value","job_id":"99b7d5ef61e24389ea2edf8c3f209856","time":55606,"worker":"misp:14872"} []

### CODE REVIEW

**Comment by iglocska** [comment]
Thanks a lot!

**Comment by iglocska** [comment]
Reverted this, there are valid reasons not to have a uuid (initial org, pull from a 2.3 instance).

**Comment by sfossen** [comment]
this fixes an actual crash, which breaks syncing, because the generateUUID is not called unless it is a locally created organization, which why I added the check and return after the generate should have been called. The other way I saw was to remove that local check, but that seemed more wrong.

**Comment by sfossen** [comment]
@iglocska this blocks the save which fails when the uuid for an org is not set, another fix would be to add a default null to the SQL.

**Comment by iglocska** [comment]
Sorry, am currently travelling abroad so a bit strapped for time to dig too
deep into it, but will definitely try to get around to it soon. A local or
with no uuid should be valid, indeed making the field nullable on an SQL
level would probably be the best solution, but I need to check why you have
failures and why we're not seeing them. Could be that either the SQL
install scripts diverged from the upgrade scripts or something, so best to
figure out how we ended up in this situation.

**Comment by sfossen** [comment]
@iglocska also at FIRST, maybe we can talk if you have free time.

**Comment by sfossen** [comment]
@iglocska I think this was caused by the other patch I submitted where the related event was not adding the UUID to orgs, but if it's possible to not have the UUID because of older versions ,then the NULLable field would does make the most sense.

**Comment by iglocska** [comment]
Indeed, makes sense. Yeah just nudge me whenever you run into me! I am
currently sitting next to the hall where the keynote was on the sofas to
the left when you exit it.

**Pull request merged**
