### PR TITLE
Update defaults.json (Phishtank - Exclude through regex)

### PR DESCRIPTION
**Pull request by eCrimeLabs**
Updated Phishtank feed with regex to exclude Phishtank url's
\/^http:\\\/\\\/www.phishtank.com\/i

## Generic requirements in order to contribute to MISP:

* One Pull Request per fix/feature/change/...
* Keep the amount of commits per PR as small as possible: if for any reason, you need to fix your commit after the pull request, please squash the changes in one single commit (or tell us why not)
* Always make sure it is mergeable in the default branch (as of today 2016-06-03: branch 2.4)
* Please make sure Travis CI works on this request, or update the test cases if needed
* Any major changes adding a functionality should be disabled by default in the config

#### What does it do?

If it fixes an existing issue, please use github syntax: `#<IssueID>`

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by eCrimeLabs** [comment]
Added the following regex to remove attributes being created with phishtank URL
```
\/^http:\\\/\\\/www.phishtank.com\/i
```

**Comment by adulau** [comment]
Is the JSON file parseable? It seems travis died on the json loading when verifying the default feed. Thanks a lot

**Comment by eCrimeLabs** [comment]
Think it is an "\"-escape issue I'll dig into it

**Review by eCrimeLabs — COMMENTED** [review]
Bugfix of the missing "\"

**Comment by iglocska** [comment]
Thanks a lot!

**Comment by adulau** [comment]
Yeah! Thank you.

**Pull request merged**
