### PR TITLE
fix: [db] rename org_blacklists to org_blocklists everywhere

### PR DESCRIPTION
**Pull request by RichieB2B**
The old name `org_blacklists` was still present in several install files.

### CODE REVIEW

**Comment by adulau** [comment]
Thank you very much!

**Comment by adulau** [comment]
Sorry I revert it. Because the SQL file is used an initial state for applying the updates via the updater. So it should be fine at the first run of the updater.

**Comment by RichieB2B** [comment]
Not according to the db_version at https://github.com/MISP/MISP/blob/2.4/INSTALL/MYSQL.sql#L1481
MYSQL.sql is at db_version 61 but the rename was done in db_version 56. So there is no need for org_blacklists to exist in MYSQL.sql anymore. The current MYSQL.sql  creates both org_blacklists and org_blocklists which never makes sense.

See https://github.com/MISP/MISP/blob/2.4/app/Model/AppModel.php#L1415

**Comment by mokaddem** [comment]
Hey @RichieB2B you were absolutely right!
That `org_blacklists` modification was overlooked when updating the sql file.
However for the Postgresql one, the `db_version` is way older than 56 so these changes should not be done there.
Thanks for your feedback!

**Pull request merged**
