### PR TITLE
Add new types in persistence category

### PR DESCRIPTION
**Pull request by Karneades**
I would like to add two new types in the persistence category. Two often used malware persistence mechanisms are services and scheduled task (or cron jobs).

Tested with MISP 2.4 and no DB change is needed.

I will make a dedicated pull request for [PyMISP](https://github.com/MISP/PyMISP/blob/master/pymisp/data/describeTypes.json).

#### Release Type:
- [ ] Major
- [X] Minor
- [ ] Patch

### CODE REVIEW

**Comment by Karneades** [comment]
I haven't saw the wiki article [Categories-&-Types-changes-CheckList](https://github.com/MISP/MISP/wiki/Categories-&-Types-changes-CheckList) until now.

**Comment by Karneades** [comment]
@SteveClement do you consider merging the PR?

**Comment by adulau** [comment]
Thanks for the PR. It's in MISP as `windows-scheduled-task`, `windows-service-name` and `windows-service-displayname`.

**Comment by Karneades** [comment]
> Thanks for the PR. It's in MISP as `windows-scheduled-task`, `windows-service-name` and `windows-service-displayname`.

Yes, in artifact dropped, but it's currently still missing in "Persistence mechanism" which it should be part of, similar to filename, regkey etc. It should be possible to clearly mark it as persistence mechanisms which is not the same as artifact dropped (for me) as it is relevant for analysis.

Why not putting it there too? I did a more generic naming than the `'windows-scheduled-task', 'windows-service-name', 'windows-service-displayname' as it also covers other OS than windows.

**Pull request closed without merging**
