### PR TITLE
Pin python dependencies

### PR DESCRIPTION
**Pull request by ostefano**
Pin python dependencies (minimum versions as per diagnostic page and/or urgent fixes)

Open questions:
- Should I remove pip from list of dependencies used (theoretically) by tests?
- Should I change the doc and edit the install script?
- Should I split requirements.txt into two files (so the two sets of dependencies are separate)?

### CODE REVIEW

**Comment by ostefano** [comment]
I would remove `pip` from list of deps used (theoritically) by tests.

**Comment by ostefano** [comment]
CC @iglocska @Rafiot

**Comment by ostefano** [comment]
Should I change the doc and edit the install script?

**Comment by ostefano** [comment]
Also, happy to split requirements.txt into two files (so the two sets of deps are separate)

**Comment by oivindoh** [comment]
Probably want to pin specific or major.minor rather than greater than - bit these pins will surely improve delivery quality

**Comment by iglocska** [comment]
Thanks a lot!

**Pull request merged**
