### PR TITLE
chg: improve logging, use HttpSocket instead of file_get_contents() f…

### PR DESCRIPTION
**Pull request by righel**
#### What does it do?
Improve AadAuth plugin logging.

triggered by #8403

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by righel** [comment]
@cudeso : It would be awesome if you could take a look at this.

**Comment by cudeso** [comment]
Hello @righel , great work! I've put a reminder in my schedule to have a look in the end of the week of the 18-Jul (no availabilities earlier) ; I'll check and provide feedback!

**Comment by MarkJaroski** [comment]
I had hoped to see that this would fix authentication for installations which sit behind a forward proxy, but apparently that's not the case. It would be nice to add the proxy configuration from the config file to each instantiation of the HttpSocket, or perhaps even creating a single instance.

**Comment by cudeso** [comment]
@righel For me this looks very good. The code certainly looks cleaner and the debug messages help a lot when you setup the plugin (I did a new install on a demo environment to test it from scratch). Thank you for the nice work!

**Comment by righel** [comment]
Thanks a lot @cudeso for taking a look !

**Pull request merged**
