### PR TITLE
new: [misp-workflow-modules] Splunk HEC export Module implemented

### PR DESCRIPTION
**Pull request by Benni0**
#### What does it do?
This commit implements a Splunk HEC export workflow module, which can be used in MISP workflows to send event data to a Splunk HTTP Event Collector.

New Pull request for #8834 because of missing branch.

#### Questions

- [ ] Does it require a DB change?
- [x] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by mokaddem** [comment]
Hey!
Thanks a lot for you pull request!
I merged it in `develop` (4adcf06b1cfe64313762c2ac9b8c179745f2b044) and did some (**untested** as I don't have a Splunk running) refactoring in f179b2db7a3554ae23c80efe98fd361e08df0b8c.

It would be great if you could test the changes and see if it's still compatible!
Once again, thank you for your contribution!

**Comment by Benni0** [comment]
Hi,
I've reviewed and tested the refactored code. My first thought of implementing this was indeed deriving it from the web-hook module, but I wasn't sure if changing your module would be a good idea.
The refactoring is fine, but we need the top level event in the data structure, because splunk requires that.
I've fixed this in my development branch 8eb26b7, where I've also added the possibility to define the source type.

Should I create a new pull request, or sould I merge it in my feature branch, which would affect my existing pull request  (#8835).

**Comment by mokaddem** [comment]
Hey!
Indeed starting from the webhook module seems sane and adding support of more functionalities such as passing headers is even better! :wink: 
For your changes, I'd merge the current state of `develop` in your PR branch (`Benni0:feature/wf_splunk_hec_exporter`), merge the changed you made in https://github.com/Benni0/MISP/commit/8eb26b7a9d67c35b1ba90046d1a276bb92654138 then push it.
Thanks!

**Comment by Benni0** [comment]
Hi,
I've merged the develop branch in my PR branch which also have added all changes from the MISP develop branch to my PR branch.
I hope this is ok.

**Comment by adulau** [comment]
@mokaddem could we merge it?

**Comment by mokaddem** [comment]
Just merged the branch in `develop` along with some indentation with (69e3948deaf01cd417b61c55cd059bf6d5650d1e).
It will be integrated in the next release that is coming shortly.
Once again @Benni0, many thanks for your contribution!
Cheers!

**Pull request merged**
