### PR TITLE
fixed the documentation (automation) page. The JSON URL was wrong

### PR DESCRIPTION
**Pull request by aaronkaplan**

### CODE REVIEW

**Comment by Rafiot** [comment]
@iglocska is this pull request still relevant? or already fixed?

**Comment by aaronkaplan** [comment]
@iglocska : pull request is still okay? If so, can we merge it and close it? Thx.
Also, I added the discussed UPDATE.txt file changes (chmod -R)

**Comment by Rafiot** [comment]
Can you to the pull request against the branch 2.4, please? master is the old 2.3 and should not be used anymore.

**Comment by iglocska** [comment]
Ah there's no need, I've merged it into 2.4, forgot to close it.

**Pull request closed without merging**
