### PR TITLE
chg: [UI] Replace famfamfam flags icons with unicode version

### PR DESCRIPTION
**Pull request by JakubOnderka**
## What does it do?

* Unicode flags are nicer and supports HiDPI displays.
* They don't require additional CSS and PNG file.

## Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by iglocska** [comment]
Hmm, under Firefox it works well, but under Chrome it gets replaced with a unicode 2 character representation :(

**Comment by JakubOnderka** [comment]
> Hmm, under Firefox it works well, but under Chrome it gets replaced with a unicode 2 character representation :(

I just tested it in Firefox :/ I will check also in Chrome, thanks for testing.

**Comment by iglocska** [comment]
Standardisation going wrong again - this is why we can't have nice things.

**Comment by JakubOnderka** [comment]
> Standardisation going wrong again - this is why we can't have nice things.

This screenshot is from latest Chrome on macOS. What kind of OS did you use?

**Comment by iglocska** [comment]
I'm on kubuntu. Is it an OS font level issue? That's even more annoying...

**Pull request closed without merging**
