### PR TITLE
add direct LDAP auth

### PR DESCRIPTION
**Pull request by righel**
#### What does it do?

Add LDAP authentication as a plugin with a direct connection to an LDAP server (no Apache Basic Auth required).

closes https://github.com/MISP/MISP/issues/5742

based on the `ApacheAuthenticate` component by @truckydev

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by arteta22000** [comment]
big new feature, thanks for that!
@righel  Could you add an option related to ldapS .
Especially for CA certificate management (self-signed).   https://andreas.heigl.org/2020/01/31/handle-self-signed-certificates-with-phps-ldap-extension/ 

example:

>         // Note: All TLS options must be set before ldap_connect is called
>         if ($this->ldapURLType != "standard") {
>             ldap_set_option(null, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_HARD);
>             ldap_set_option(null, LDAP_OPT_X_TLS_CACERTFILE, '/usr/local/etc/ssl/cert.pem');
>         } else {
>             ldap_set_option(null, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_NEVER);
>         }

https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php

**Comment by righel** [comment]
> big new feature, thanks for that! @righel Could you add an option related to ldapS . Especially for CA certificate management (self-signed). https://andreas.heigl.org/2020/01/31/handle-self-signed-certificates-with-phps-ldap-extension/
> 
> example:
> 
> > ```
> >     // Note: All TLS options must be set before ldap_connect is called
> >     if ($this->ldapURLType != "standard") {
> >         ldap_set_option(null, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_HARD);
> >         ldap_set_option(null, LDAP_OPT_X_TLS_CACERTFILE, '/usr/local/etc/ssl/cert.pem');
> >     } else {
> >         ldap_set_option(null, LDAP_OPT_X_TLS_REQUIRE_CERT, LDAP_OPT_X_TLS_NEVER);
> >     }
> > ```
> 
> https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php

Sure! Shouldn't be too big of a change, I'll get into that.

**Comment by arteta22000** [comment]
@righel small question, I've just tested, everything works fine, but can you log in on the ui  using the uid ldap field rather than email? currently on the webui side, I get a message: "_please enter a valid email address_" when I try to log in with uid.

**Comment by righel** [comment]
> @righel small question, I've just tested, everything works fine, but can you log in on the ui using the uid ldap field rather than email? currently on the webui side, I get a message: "_please enter a valid email address_" when I try to log in with uid.

Hi,
MISP requires the username to be an email, several features rely on this for sending information to the user via email. I would have to evaluate the impact of dropping this requirement without breaking other features.

**Comment by arteta22000** [comment]
ok, thanks @righel  , another question:
I'm trying the “ldapDefaultRoleId” parameter:

> 'LdapAuth' =>
>   array (
>     'ldapServer' => 'ldaps://xxxxxxxx',
>     'ldapDn' => 'dc=ssa',
>     'ldapReaderUser' => 'uid=xxxxxxxa',
>     'ldapReaderPassword' => 'xxxxx5',
>     'ldapTlsRequireCert' => 'LDAP_OPT_X_TLS_NEVER',
>     'ldapDefaultRoleId' =>
>     array (
>       'eng-xxxxx' => 1,
>       'users_xxxxx' => 1,
>       'zzzzzzzzzzzzzzz' => 3,
>     ),
> ),

i have this error:

image

Maybe there's something I didn't understand. Is the field ldap memberOf used? example:

> dn: uid=xxxxxxx
userPassword::
objectClass: top
objectClass: inetOrgPerson
objectClass: inetUser
objectClass: posixAccount
objectClass: shadowAccount
objectClass: ssaAccount
objectClass: organizationalPerson
objectClass: person
objectClass: ldapPublicKey
memberOf: cn=eng-xxxxxxxx
employeeNumber: glexxxxxx
description: xxxxxx
gidNumber: 32000
uidNumber: 12393
uid: glxxxxx
cn: guxxxxxxt

**Comment by righel** [comment]
Hello @arteta22000, sorry for the late reply.
Your `LdapAuth.ldapDefaultRoleId` setting looks okay.
Can you enable the debug mode byt setting `LdapAuth.debug` to `true` settings and share the last 100 or so lines of /var/www/MISP/app/tmp/logs/error.log after you try to log-in and get this error?

**Comment by arteta22000** [comment]
@righel  I cannot activate the ldap debug mode I think ?
I have this conf in config.php:

```
'LdapAuth' =>
  array (
    'ldapServer' => 'ldaps://xxxxx',
    'ldapDn' => 'dc=xxxxxx',
    'ldapReaderUser' => 'uid=xxxxxxl,o=transversal,dc=xxxx',
    'ldapReaderPassword' => 'xxxxx',
    'debug' => 'true',
    'ldapTlsRequireCert' => 'LDAP_OPT_X_TLS_NEVER',
    'ldapDefaultRoleId' =>
    array (
      'engcxxx' => 1,
      'users_l3xxxx' => 1,
      'zzzzzzzzzzzzzzz' => 3,
    ),
),
);
```

but I've only that in log:

```
2025-01-07 13:11:09 Error: [UnauthorizedException] User could not be authenticated by LDAP.
Request URL: /users/login?_=1736246463875
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(698): LdapAuthenticate->getUser()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_getUser()
#2 /var/www/MISP/app/Controller/AppController.php(1320): AuthComponent->startup()
#3 /var/www/MISP/app/Controller/AppController.php(270): AppController->_loadAuthenticationPlugins()
#4 /var/www/MISP/app/Controller/UsersController.php(29): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): UsersController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(687): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#10 {main}

2025-01-07 13:11:40 Error: [UnauthorizedException] User could not be authenticated by LDAP.
Request URL: /users/login?_=1736256247855
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(698): LdapAuthenticate->getUser()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_getUser()
#2 /var/www/MISP/app/Controller/AppController.php(1320): AuthComponent->startup()
#3 /var/www/MISP/app/Controller/AppController.php(270): AppController->_loadAuthenticationPlugins()
#4 /var/www/MISP/app/Controller/UsersController.php(29): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): UsersController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(687): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#10 {main}
```

**Comment by righel** [comment]
Change set the setting  `Security.debug` to `true`. Go can do this via the UI coing to `/servers/serverSettings/Security`

There is an additional command line test script for debugging LdapAuth, see: 
* https://github.com/MISP/MISP/tree/2.5/app/Plugin/LdapAuth#debugging
* https://github.com/MISP/MISP/blob/2.5/app/Plugin/LdapAuth/Controller/Component/Auth/TestLdapAuth.php

**Comment by arteta22000** [comment]
i just did it via the UI . i have the error in UI now:

image

but no more debug logs in app/tmp/logs/error.log

**Comment by arteta22000** [comment]
it's ok, the problem was caused by my ldap server.

**Pull request merged**
