### PR TITLE
Proxy support for SyncTool

### PR DESCRIPTION
**Pull request by RichieB2B**
Fix for #368. If you need HTTPS support via a proxy you will need cakephp/cakephp#6098

### CODE REVIEW

**Comment by RichieB2B** [comment]
This is pretty complete now. It only calls configProxy() in setupHttpSocket() and uses setupHttpSocket() for all diagnostics including checking the MISP version.

**Comment by iglocska** [comment]
That looks fantastic, thanks a lot! Will try to go through all your patches soon and merge them!

**Comment by elhoim** [comment]
Thanks a lot!

**Comment by adulau** [comment]
FYI, It seems the code is not supporting SNI (tested on our instances having SSL/SNI enabled) @RichieB2B will have a look. If you want to have a look too, feel free.

**Comment by RichieB2B** [comment]
The SNI problem is actually in https://github.com/cakephp/cakephp/pull/6098. This pull request can be merged as is.

**Comment by RichieB2B** [comment]
Since the master or cakephp changed to 3.0.0 this pull request now depends on https://github.com/cakephp/cakephp/pull/6146

**Pull request merged**
