### PR TITLE
slightly modified logroate config which rotates all logs in MISP/app/…

### PR DESCRIPTION
**Pull request by ag-michael**
…tmp/logs when they reach a 50MB limit, with maximum log size set to 500M. rotation is checked every hour

## Generic requirements in order to contribute to MISP:

* One Pull Request per fix/feature/change/...
* Keep the amount of commits per PR as small as possible: if for any reason, you need to fix your commit after the pull request, please squash the changes in one single commit (or tell us why not)
* Always make sure it is mergeable in the default branch (as of today 2016-06-03: branch 2.4)
* Please make sure Travis CI works on this request, or update the test cases if needed
* Any major changes adding a functionality should be disabled by default in the config

#### What does it do?

If it fixes an existing issue, please use github syntax: `#<IssueID>`

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by ag-michael** [comment]
slightly modified logroate config which rotates all logs in MISP/app/tmp/logs when they reach a 50MB limit, with maximum log size set to 500M. rotation is checked every hour.

**Comment by SteveClement** [comment]
> slightly modified logroate config which rotates all logs in MISP/app/tmp/logs when they reach a 50MB limit, with maximum log size set to 500M. rotation is checked every hour.

I wold prefer a daily check.
For the rest it looks ok.
Perhaps @iglocska wants to give the final go.

**Comment by ag-michael** [comment]
@SteveClement Daily is fine, I used hourly because if something is filling up logs fast you'd want it rolled before it had a chance to impact disk space usage significantly.

**Comment by SteveClement** [comment]
Cool, I was more coming from the side of having the ease to debug any issues without decompressing random files ;)

**Pull request merged**
