### PR TITLE
Add SMIME encryption & signing 

### PR DESCRIPTION
**Pull request by devnull-**
Hello all,

The mission of this patch is to add the support of SMIME [1](https://en.wikipedia.org/wiki/S/MIME) in order to improve the solutions to encrypt & sign emails in MISP :)

This patch works when:
- SMIME enabled & GPG disabled: In this context, all emails will be sent encrypted and signed using S/MIME. If the user doesn't set a public certificate (for encipherment), he will receive an email (clear text) to invite him to connect to MISP in order to obtain the detail on the published event (the template for this email is attached to this "Pull request").
- GPG & SMIME enabled: By default, GPG is always preferred :). Thus, if the user sets a GPG key and a public certificate in this profile, he will receive all email encrypted & signed using GPG. If the user doesn't set a GPG key but has set a public certificate, the emails will be encrypted & signed using S/MIME. Of course, if no GPG key and public certificate are set, he will receive an email (clear text) to invite him to connect to MISP in order to obtain the detail on the published event (the template for this email is attached to this "Pull request").
- SMIME disabled: In this context, the email will be sent encrypted & signed using GPG, if GPG is enabled. If no GPG key is set in the user profile, the user will receive an email (clear text) to invite him to connect to MISP in order to obtain the detail on the published event (the template for this email is attached to this "Pull request"). 

The different steps to install this patch is defined the INSTALL.txt (section: ' 9/ SMIME patch')

 At the moment, I currently use this patch (and it's working well) but this patch is still in the "beta phase" and don't blame me for bugs and dirty hacks in the code.

devnull-

[2]: At the moment, AES_256_CBC is used to encrypt the email

---

```
Hello, 

The event number 43 was published on the MISP platform. 

Since no GPG/PGP key or public certificate is set in your MISP profile, you can not directly receive the information in an encrypted email. 
You can fill out you profile with your GPG/PGP key or public to receive encrypted email. 

To access to the event involved, please click on the following link:
URL    : https://misp.xxx.xxx.com/events/view/43


Best regards,

XXXXXX  xxxx

```

---

### CODE REVIEW

**Comment by adulau** [comment]
Hi @devnull- 
Looks very promising. Did you try to merge/update the patch the current master branch? 
Thank you very much.

**Comment by Rafiot** [comment]
@devnull- poke?

**Comment by devnull-** [comment]
Hello @adulau & @Rafiot,

I'm sorry for the long delay of my reply :(
I'm still maintaining the patch to support SMIME. Could you give a couple of day to clean the code and update this pull request before merging/updating my patch with the current master branch ?

Thank you for your replies ;) and don't hesitate to contact me if you need some help and if you have some question about the S/MIME patch.

devnull-

**Comment by Rafiot** [comment]
Very good news! We are looking forward in having this functionality in the application.

**Comment by Rafiot** [comment]
Ohai, how does it goes? :)

**Comment by Rafiot** [comment]
Poke? :)

**Comment by Rafiot** [comment]
@devnull- any chance you can get it into 2.4?

**Comment by jaegeral** [comment]
Could / should anyone else pick that up?

**Comment by devnull-** [comment]
Hello @Rafiot,

I'm still maintaining the patch to support SMIME with the last MISP version. I'll force myself to update this pull request, next week :)

Thank you for your replies and your messages ;) and don't hesitate to contact me if you need some help and if you have some question about the S/MIME patch.

devnull-

**Comment by Rafiot** [comment]
@devnull- \o/ that would be awesome if you could update the PR, _lots_ of people are asking for that functionality.

**Comment by devnull-** [comment]
@Rafiot : I vow to update this PR next week ;)

**Comment by Rafiot** [comment]
That would be awesome :)

**Comment by devnull-** [comment]
Pull request updated for [MISP 2.4](https://github.com/MISP/MISP/pull/1057)

**Pull request closed without merging**
