### PR TITLE
Changed regex to validate date and make sure the right dates are validated

### PR DESCRIPTION
**Pull request by stevengoossensB**
Changed regex to validate date and make sure the right dates are validated

Changes to be committed:
	modified:   AttributesController.php

### CODE REVIEW

**Comment by adulau** [comment]
@iglocska Do you think it could be possible to merge this as a hotfix?

**Comment by iglocska** [comment]
The date part definitely, the changes to the threat level would change the
meaning of a lot of the data in there though...

**Comment by adulau** [comment]
Sorry my bad. I was only talking about the date verification. We can discard the other part, I just got the confirmation from @stevengoossensB Thanks a lot.

**Comment by iglocska** [comment]
Sounds good, I am doing some more changes to it as other exports are
currently not validating the from / to field for the API at all, I'll have
a hotfix with this and some other things up later tonight!

**Comment by iglocska** [comment]
Added a while back

**Pull request closed without merging**
