### PR TITLE
SSL client certificates for sync servers

### PR DESCRIPTION
**Pull request by RichieB2B**
Fixes https://github.com/MISP/MISP/issues/1253
It works ok, but setting ['Server']['client_cert_file'] upon upload does not seem to work. Could this be an issue with caching the data model?
#### Questions
- [x] Does it require a DB change?
- [x] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?
#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by iglocska** [comment]
Indeed, there will be a caching issue with that. To fix it manually you can clear out myapp\* from /var/www/MISP/app/tmp/cache/persistent/ and /var/www/MISP/app/tmp/cache/models/

I cannot check it and merge it just yet, we're currently at FIRST and it's a bit hectic, but I'll look into it asap. I can also tie it into the auto-upgrade mechanism that cleans out the caches automatically.

Thanks a lot for doing a PR for this, very nice upgrade!

**Comment by RichieB2B** [comment]
Removing the caches did not help. ['Server']['client_cert_file']  is still not saved. Must be something with my code. :-(

**Comment by iglocska** [comment]
Damn. Will try to have a look at it, am currently in Korea, but I should be
back next Thursday or Friday.

**Comment by rotanid** [comment]
Hi @RichieB2B , this PR contains a change of a variable name, could you please split that apart into a separate PR if you think it's necessary? it has nothing to do with the client certificates, so we should keep it separated.

your request also has merge conflicts now and after everything is working, ideally it should only contain one commit (so after a merge, it is clear in the commitlog which commit introduced your feature - not one commit adding some stuff that the next commit is immediately changing)

if you need assistance on how to update this pull request (git rebase -i ...  and git push --force are your friends for example), feel free to ask me via gitter.

**Comment by RichieB2B** [comment]
Thanks @rotanid for the suggestions. I think I have addressed all of them in the new commit. This patch seems to work fine, except that ['Server']['client_cert_file'] is not saved in MySQL when a client certificate is uploaded. If you find why I will update the PR.

**Comment by iglocska** [comment]
Very sorry for all the delays on this, will try to go through it in the near future.

**Comment by RichieB2B** [comment]
Of course I spotted the typo 2 minutes after posting my previous comment. The PR is fine now. Can you reopen it?

**Comment by iglocska** [comment]
Done!

**Comment by RichieB2B** [comment]
Everything seems to work ok now. Including the automatic schema update. :-) 
This is ready for merging unless you have more suggestions of course.

**Comment by RichieB2B** [comment]
This PR didn't make it into 2.4.50 :-( Any chance for 2.4.51 ?

**Comment by iglocska** [comment]
Sorry for the delay, we had to fast-track 2.4.50. Definitely and 2.4.51 should come very soon, will make sure it's in there.

**Comment by RichieB2B** [comment]
I've updated my patch to merge smoothly with the current 2.4 branch.

**Comment by iglocska** [comment]
Oh it's already in 2.4.51, which we'll release today!

**Comment by iglocska** [comment]
What are the new changes compared to the old commit?

**Comment by RichieB2B** [comment]
- Removed the database update (already committed)
- Removed patches of files no longer in git (upgrade_2.4.sql, schema.php)
- Fixed small bug I introduced with [delete_cert](https://github.com/RichieB2B/MISP/blob/936948919e8e634110bf097c8763f7aae938d91e/app/Controller/ServersController.php#L324)

**Comment by RichieB2B** [comment]
So if you reverse the true and false [here](https://github.com/RichieB2B/MISP/blob/936948919e8e634110bf097c8763f7aae938d91e/app/Controller/ServersController.php#L324) all should be fine.

**Comment by iglocska** [comment]
I just checked it seems correct on 2.4.51 already, so no change needed :)

**Comment by RichieB2B** [comment]
Looks ok indeed.

**Pull request closed without merging**
