### PR TITLE
Schema diagnostic improvement

### PR DESCRIPTION
**Pull request by mokaddem**
- Improved UI: show ``datasource`` and hide non-critical warnings
- Consider quoted ``default_value`` equal to non-quoted one.
    - e.g.: ``network === 'network'`` (see #5441)

If you have additional whitelist requests or ideas, feel free to say

# Should mitigate/Fix
- #5441
- #5457
- #5455

### CODE REVIEW

**Comment by eCrimeLabs** [comment]
Related to this I can confirm on #5441 that I'm experiencing the same issue on a Debian 10 new installation 
Schema_status_red

**Comment by iglocska** [comment]
Looks good, thanks a lot!

**Comment by otgrkiss** [comment]
Same error for me. Cent OS 7 and Maria DB. And we just updated from 118 to 119 15 minuets ago.

**Comment by iglocska** [comment]
This should be fixed now, please update to the latest version.

**Comment by otgrkiss** [comment]
Well we did just 30 minuets ago. We are on hash 53482ff76c409d0ebf944853fdae4d8483a5b6f7

**Comment by iglocska** [comment]
Interesting, can you paste the output that you get?

**Pull request merged**
