### PR TITLE
Scheduled task to fetch feeds, fixes issue #1523

### PR DESCRIPTION
**Pull request by panzertime**
Added a Scheduled Task for automatically fetching all enabled feeds on such-and-such a given interval.

See issue https://github.com/MISP/MISP/issues/1523

### CODE REVIEW

**Comment by adulau** [comment]
Thanks a lot for the pull-request but I suppose this was solved in https://github.com/MISP/MISP/commit/bcbee05e2f39b07704cd7663237812ab5a724803 ?

**Comment by panzertime** [comment]
Whups

**Comment by adulau** [comment]
@panzertime but if you have some time, there is a bug in the version from @iglocska meaning the scheduler is not properly called. It's a nice challenge ;-)

**Comment by panzertime** [comment]
I'll take a look!

**Comment by panzertime** [comment]
I believe I've fixed the bug, I'll create a new PR

**Pull request closed without merging**
