### PR TITLE
New option "internal tag" for tag sharing on internal instance

### PR DESCRIPTION
**Pull request by lucamemini**
Added support for "internally exportable tags" #2010 :)

### CODE REVIEW

**Comment by lucamemini** [comment]
Cattura

**Comment by iglocska** [comment]
Argh. What exactly is it doing? I have something that I'll push out in the release tomorrow that might be very similar :'(

**Comment by iglocska** [comment]
image

**Comment by lucamemini** [comment]
Doh!
hqdefault

**Comment by adulau** [comment]
@lucamemini This has been merged in 2.4. 2a059f7b3171e3f3f8b26de6b8e7b5594e4ac3ee 

Let us know what you think about it and if this solves your issue. Thanks a lot for your contribution.

local-tags

**Comment by lucamemini** [comment]
@adulau I will try in next days... thx :-)

**Comment by lucamemini** [comment]
@adulau @iglocska Hi guys,
I tested your patch but this is different from my patch.

My patch works on tag table adding new state "internal" (currently states are only exportable and hidden).
The new tag state driving the synchronization process with remote server. if remote server configuration  had flag "internal" active the tag is pushed, without flag the tag is stripped. 

Thx! :)

**Comment by iglocska** [comment]
A stupid question, how is that different from exportable? :$

**Comment by iglocska** [comment]
OK, I got it I think. Would the new system with local tags work for you if they would not get stripped when pushing to internal instances? (I actually wanted to add that but forgot...)

**Comment by lucamemini** [comment]
Yeppa... look this function:

```
    // since we fetch the event and filter on tags after / server, we need to cull all of the non exportable tags
    private function __removeNonExportableTags($data, $dataType, $server)
    {
        if (!empty($data[$dataType . 'Tag'])) {
            foreach ($data[$dataType . 'Tag'] as $k => $tag) {
                if (($server['Server']['internal'] == 1) && ($tag['Tag']['internal'] == 1)) { // Internal server, Internal Tag => Export
                    unset($tag['org_id']);
                    $data['Tag'][] = $tag['Tag'];
                } else if (($server['Server']['internal'] == 0) && ($tag['Tag']['internal'] != 1) && ($tag['Tag']['exportable'] == 1)) { // External Server, not internal tag,  exportable tag => Export
                    unset($tag['org_id']);
                    $data['Tag'][] = $tag['Tag'];
                } else if (($server['Server']['internal'] == 1) && ($tag['Tag']['exportable'] == 1)) { // Internal Server, Exportable tag => Export
                    unset($tag['org_id']);
                    $data['Tag'][] = $tag['Tag'];
                } else { // Drop tag (tag is not exportable) 
                    unset($data[$dataType . 'Tag'][$k]);
                }
            }
            unset($data[$dataType . 'Tag']);
        }
        return $data;
    }
```

> OK, I got it I think. Would the new system with local tags work for you if they would not get stripped when pushing to internal instances? (I actually wanted to add that but forgot...)

Lol :-)
BTW, yes I have 3 misp server linked with "internal instance" flag active... but and I need use internal tag to exchange additional info with this costellation :-)

**Comment by RichieB2B** [comment]
Indeed: local tags are synced to local servers only. Non-exportable tags are never synced.

**Comment by lucamemini** [comment]
Any update? :)

**Comment by iglocska** [comment]
Sorry, was away on holidays for the past 2 weeks, will be back starting
Monday - expect delays ;)

**Comment by tom564** [comment]
Being able to export local tags to internal MISP servers would be really useful for us as well

**Comment by lucamemini** [comment]
up :*

**Comment by github-germ** [comment]
+1 --> This would help if we move to local tags as per https://github.com/MISP/MISP/issues/5204#issuecomment-537043057

Thanks!

**Comment by iglocska** [comment]
For our records: The plan is to refactor local tags to move from internal to internal instance.

**Pull request closed without merging**
