### PR TITLE
deleteSelected: fix request method check

### PR DESCRIPTION
**Pull request by rotanid**
if i understood this part correctly, it should check if either POST or AJAX is used.
without the suggested change, the if-clause would always return true and hence the Exception would always be thrown, because the request can't be POST and AJAX at the same time, can it?

### CODE REVIEW

**Comment by iglocska** [comment]
Delete selected is for POSTing an AJAX request (it's when you check a few rows and click delete on top). The check says that if you've somehow arrived there via a request that is not a POST or not via AJAX then throw an exception.

**Comment by rotanid** [comment]
- so request->is('post') and request->is('ajax') can be true for one single request?
- isn't the is('post') obsolete according to your explanation?
- at least the commented out line below is obsolete ;-)

**Comment by iglocska** [comment]
Yup, both can and should be true! Basically an ajax request can be either get or post, in this case we want to ensure that it is a post request and it is arriving via ajax instead of the user manually loading up the action.

**Comment by iglocska** [comment]
The commented line is definitely obsolete though :)

**Pull request closed without merging**
