### PR TITLE
fix: [internal] Load MISP version just once in AppController

### PR DESCRIPTION
**Pull request by JakubOnderka**
## What does it do?

Small code cleanup and small speedup.

## Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

## Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by iglocska** [comment]
Thanks a lot!

**Comment by Rafiot** [comment]
This PR broke freetext import, please make a new one is needed.

**Comment by JakubOnderka** [comment]
@Rafiot Jaj, can you please provide more information? At least error message from log?

**Comment by iglocska** [comment]
This one was a nasty one, totally not your fault. We had a long standing bug that was just revealed by your PR ;) 

Quick explanation:

We've had an erroneus command in the event model:

https://github.com/MISP/MISP/commit/1b13734483ec3e3044b47e01e65f682ce013acda

What happened: We have a setting in MISP that is super seldomly used, `disable_background_jobs` that can be passed via URL parameters to temporarily disable background processing for a single request. It's almost never a good idea to use it, but for the travis tests it allows us to have the execution of the tests and their assertions happen in a linear fashion with no breaks in between.

You moving the version check a few lines further down had a weird effect:

the version check itself is in AppModel, but in order to call the function, cakePHP needs to lazy-load the model. This all of the sudden happens after the on-demand disabling of the background processing via a Configure::write() command. Lazy loading the Event model triggered the renewed load of the configuration, leading to the purging of the on-demand setting. 

I was puzzled as hell when doing this during the testing:

```
debug(Configure::read('MISP.background_jobs'));
$this->Event;
debug(Configure::read('MISP.background_jobs'));
```

and receiving different results in the two debug calls. With that resolved, I've reverted the git revert and your PR is merged back again, sorry for the confusion :)

**Comment by RichieB2B** [comment]
Hah! I remember introducing this "fix" with 886d36438ef7a0653123cb68f3f6bf79eff17d7e in 2015. Puzzled me as well why it was needed. Glad to see if finally resolved!

**Comment by iglocska** [comment]
Yeah we should be good without it. Tried via CLI command too to see if we can run into a situation where the settings are not accessible but couldn't find anything.

**Comment by iglocska** [comment]
2015 would explain it though, probably before we've had the current settings system ;)

**Pull request merged**
