### PR TITLE
fix: [internal] withCredentials property was added into $.ajaxSetup()…

### PR DESCRIPTION
**Pull request by MrBoba**
… to get rid of 403 and 302 responses

#### What does it do?

It fixes missing cookies in AJAX requests like:
 - /events/checkLocks/<ID>/<TS>
 - /threads/view/<ID>/true
 - /eventReports/index/event_id:<ID>/index_for_event:1
 - ...
I've a new MISP installation and when go into event details - issues appear.
In some cases on the backend the ajax request doesn't determine as ajax - 'X-Requested-With' header fixes this.

#### Questions

- [NO] Does it require a DB change?
- [YES] Are you using it in production?
- [NO] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by iglocska** [comment]
Nice, that should solve some annoying issues, thanks!

**Comment by iglocska** [comment]
Reverted for now, as suggested by @JakubOnderka this is a bit too lax when it comes to requests to other domains. However a new PR that only affects queries such as checkLocks specifically would be nice!

**Comment by JakubOnderka** [comment]
What browser are you using? Can you also check if you use correct domain? Because it looks like AJAX tries to send requests to another domain (cross domain requests) and thats the reason why cookies are not sent.

**Comment by MrBoba** [comment]
I am using Firefox 93.0 (64-bit). I used the machine's IP as the host and this IP is the same for regular and AJAX requests. Am I doing something wrong?

**Comment by MrBoba** [comment]
I've tried with domain and it works perfect.

**Pull request merged**
