### PR TITLE
new: [Authkeys] Add setting to mandate IP allowlist for advanced auth…

### PR DESCRIPTION
**Pull request by Wachizungu**
…keys

For review

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

### CODE REVIEW

**Comment by Wachizungu** [comment]
Not really sure how this breaks the tests, any way I can easily trigger a second run to know it's not a fluke?

**Comment by adulau** [comment]
@Wachizungu restarted, let's see.

**Comment by adulau** [comment]
If you rebase to the latest version, I bet it will be fine ;-)

**Comment by Wachizungu** [comment]
hurray, magic :D! Thanks.

**Comment by adulau** [comment]
Thank you!

**Pull request merged**
