### PR TITLE
Install python dependencies via Pipfile instead of manually cloning / installing them

### PR DESCRIPTION
**Pull request by sim0nx**
## Generic requirements in order to contribute to MISP:

* One Pull Request per fix/feature/change/...
* Keep the amount of commits per PR as small as possible: if for any reason, you need to fix your commit after the pull request, please squash the changes in one single commit (or tell us why not)
* Always make sure it is mergeable in the default branch (as of today 2016-06-03: branch 2.4)
* Please make sure Travis CI works on this request, or update the test cases if needed
* Any major changes adding a functionality should be disabled by default in the config

#### What does it do?

As discusses on gitter, it would be really nice if one could install python dependencies via a requirements.txt or Pipfile. I choose Pipfile as you are already using pipenv in travis and for PyMISP so I suppose this is the preferred way.
I used exactly the same sources and versions (any, specific refs, ...) as is defined in git submodules or documentation.

Ideally one would replace git refs by tags or pypi versions where possible.

Using pipenv a user simply does "pipenv sync" to put his virtualenv to the state the developers intended it to be. So this would be a win-win for users and developers :-).

#### Questions

- [ ] Does it require a DB change?
- [X] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by sim0nx** [comment]
Does this make sense to you ?
Please let me know if it does and what else you expect me to modify.

In case this would get merged, I would remove python related submodules.

**Comment by Rafiot** [comment]
There are a few tricks in the pymisp package that will also automatically get the proper dependencies without having them in the pipfile directly: https://github.com/MISP/PyMISP/blob/master/Pipfile

But besides that, I don't see a problem. 

Removing the submodule all together may not be a good idea as some other users may be using the fact it's there in unexpected ways and they won't like.

**Comment by sim0nx** [comment]
Thanks for the feedback. The Pipfile is not used when installing PyMISP as dependency here, but you have similar stuff in the setup.py.
With tricks you mean extras_require ?

Anything in particular I should include in the Pipfile here for PyMISP?

"fileobjects" would make sense.

BTW PyMIPS do you think it would be possible to tag releases when you make a new MISP release so that the submodule in MISP would point to a tag instead a commit-ref ?

**Comment by sim0nx** [comment]
Please let me know if you require me to adapt anything else. If not, feel free to merge :-)

**Comment by Rafiot** [comment]
Yes, I meant the `fileobjects` switch. Looks good to me, merging, thank you! 

You're making a good point regarding PyMISP and using the tagged releases instead of the commit ref. I'll see if that's possible with the submodules. 

Right now, the main reason we don't do that is because I often add new test cases and I want travis to run on them.

**Comment by sim0nx** [comment]
Thank you for merging!

Regarding PyMISP and testing; maybe one could still lock a release tag in the Pipfile. As you keep the submodule, that won't change much for the testing part you mention.

**Pull request merged**
