### PR TITLE
Clarify documentation for API calls

### PR DESCRIPTION
**Pull request by elhoim**
Clarify which fields of events are used by **to**, **from** and **last** API calls parameters.

### CODE REVIEW

**Comment by iglocska** [comment]
Thanks a lot!

**Comment by adulau** [comment]
@elhoim Usually the source of the documentation should be misp-book? Could you update it there too? We will remove the doc from the MISP code base soon and only reference back to misp-book. Thanks a lot.

**Comment by elhoim** [comment]
Oops. Error corrected.
Information added to misp-book

**Comment by adulau** [comment]
Super. Thank you very much.

**Pull request merged**
