### PR TITLE
Chg loading bars interval change

### PR DESCRIPTION
**Pull request by cristianbell**
## Generic requirements in order to contribute to MISP:
- One Pull Request per fix/feature/change/...
- Keep the amount of commits per PR as small as possible: if for any reason, you need to fix your commit after the pull request, please squash the changes in one single commit (or tell us why not)
- Always make sure it is mergeable in the default branch (as of today 2016-06-03: branch 2.4)
- Please make sure Travis CI works on this request, or update the test cases if needed
- Any major changes adding a functionality should be disabled by default in the config
#### What does it do?

In the event\export: it changes the loading bar update time from 1000 to 3000. This decreases the requests number. In the Jobs list it is already 3000. 
#### Questions
- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?
#### Release Type:
- [ ] Major
- [x] Minor
- [ ] Patch

### CODE REVIEW

**Comment by iglocska** [comment]
Could you do a separate PR for each patch? Thanks in advance.

**Comment by cristianbell** [comment]
I did :( 

I see them as 2 separate PR: 
- ```
    #1293  <https://github.com/MISP/MISP/pull/1293> Chg loading bars interval change Jun 22 <https://github.com/MISP/MISP> MISP/MISP
  ```
- ```
    #1284  <https://github.com/MISP/MISP/pull/1284> install script for ubuntu14, based on da667 (deusexmachina667@gmail.c… Jun 22 <https://github.com/MISP/MISP> MISP/MISP
  ```

**Comment by iglocska** [comment]
https://github.com/MISP/MISP/pull/1293/files

**Comment by Rafiot** [comment]
This PR contains the change for the value for the bar AND the install script. I guess the latest is there by mistake.

**Comment by cristianbell** [comment]
Yes, but that's odd. I commited the first branch, after created a second branch and commited that. Created different PR each time, v. strange.. 

Mit Freundlichen Grüßen,

Cristian Bell
Tel.: 0049 (0)172.777.8738

Please consider the environment before printing this email.
 
-----Ursprüngliche Nachricht-----
 Von: "Raphaël Vinot" [notifications@github.com]
 Gesendet: Do. 23.06.2016 03:42
 An: "MISP/MISP" [MISP@noreply.github.com]
 Kopie: "Cristian Bell" [cristian.bell@freenet.de],  "Author" [author@noreply.github.com]
 Betreff: Re: [MISP/MISP] Chg loading bars interval change (#1293)

This PR contains the change for the value for the bar AND the install script. I guess the latest is there by mistake.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
-----Ursprüngliche Nachricht Ende-----

---

Mail & Cloud Made in Germany mit 3 GB Speicher! Jetzt kostenlos anmelden

**Pull request closed without merging**
