### PR TITLE
new: Add keyboard shortcuts application-wide, managed using JSON files

### PR DESCRIPTION
**Pull request by Res260**
#### What does it do?

peek 2018-02-09 15-00

Adds the basic support for keyboard shortcuts in MISP.

See issue #2905

I'm open to suggestions for implementation changes! 

I put shortcuts for functions I use the most in MISP.

#### Questions

**Q: How do I add keyboard shortcuts?**
A: 1. Add a JSON file in `app/webroots/shortcuts` named after the page from which it will be included (for exemple `event_view.json`).
2. Set your shortcuts using this format: 
image
(`action` field is JS code) 

2. Include the keyboard shortcut config in the `.ctp` file you wish it to be used in using an `input type="hidden"` tag like this: 
image

3. Test your shortcuts.

**Q: Is it possible to customize the shortcuts once they are there?**
A: Not at the moment.

- [ No ] Does it require a DB change?
- [ No, tested locally ] Are you using it in production?
- [ No ] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by adulau** [comment]
Thank you! This is really nice. I love the idea of the clean JSON files with all the actions. Looks good to me. @iglocska what do you think?

**Comment by iglocska** [comment]
I see some potential clashes with some shortcuts (such as 'e' for navigating between events on the correlation graph) - other than that, awesome stuff. Will have a look at what we're clashing with.

**Comment by adulau** [comment]
Thank you very much. @iglocska will fix the current shortcuts in the correlation graph ;-)

**Comment by iglocska** [comment]
Yeah, luckily we never document anything so nobody knows about those shortcuts anyway ;)

**Comment by RichieB2B** [comment]
Awesome! Can we have a CTRL+f to select the search field please?

**Comment by Res260** [comment]
@adulau Thanks!

@iglocska Is there somewhere I can document these changes?

@RichieB2B My changes only support one key shortcuts at the moment. Is it a good idea to override the browser's `ctlr+f`? I'd be tempted to say no, but I guess it changes from person to person.

Regardless, it's very easy to add a shortcut, so I'd say pick another key/change the F key in `event_view.json` :)

**Comment by iglocska** [comment]
Sure, MISP book is a side project for that. If you can add it in there somewhere that would be great. I'll try to add the revised ones for the graph once I push it - but again, I am completely horrible at documenting stuff ;)

**Comment by Res260** [comment]
I'll try to take a look at that this week! As I read a while ago: Documentation is like sex: if it's bad, it's still better than nothing, and if it's good it's the best thing in the world :)

**Comment by iglocska** [comment]
Hahaha, great!

**Comment by RichieB2B** [comment]
@Res260 you're right, CTRL+f is not the best choice. Maybe "s" for Search?

**Comment by iglocska** [comment]
You can already jump to it by using alt+f4, give it a shot. ;)

But yeah, "s" sounds good.

**Comment by Res260** [comment]
Alright, I'll do that as well!

**Comment by iglocska** [comment]
Thanks a million!

**Comment by Res260** [comment]
Thanks to you for doing the harder parts haha

**Comment by iglocska** [comment]
Nobody will ever convince me that JavaScript isn't the harder part ;)

**Comment by Res260** [comment]
@RichieB2B Are you talking about this?
image

**Pull request merged**
