### PR TITLE
chg: [db_schema] Add constraint on UUID for Attribute, Object and Event

### LINKED ISSUE #6166: Proposal can be accepted multiple times and then cannot be deleted
# Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.129

### Expected behavior
- Proposals cannot be accepted/inserted multiple times.
- If accepted multiple times, it is possible

### Actual behavior
- Proposal was accepted multiple times.
- Cannot delete the created attributes (not any of them).

### Steps to reproduce the behavior
- Use org A to create and publish an event with some attributes.
- Use org B to create a proposal with the same value as one of the existing attributes but using a different type.
- Use org A to click multiple times on 
The multiple insertion might be due to the background processing of the deletion of proposal + creation of attribute.

Event 63120 on MISPpriv is the event that triggered this bug report (created attributes 10027975 & 10027976). The multiple values created are 100% me clicking multiple times.

### PR DESCRIPTION
**Pull request by mokaddem**
Add constraints on UUID for Attribute, Object and Event as well as clean up methods taking care of duplicates

- Fixes https://github.com/MISP/MISP/issues/6166
- Probably mitigate https://github.com/MISP/MISP/issues/6034

### CODE REVIEW

**Comment by JakubOnderka** [comment]
This will not help with #6034, because the problem there is duplicate value, not duplicate UUID :/

**Comment by iglocska** [comment]
@JakubOnderka - indeed, this is fixing another issue (the duplicates popping up when acepting proposals in close succession). For the duplicates of attributes we need another strategy, however the uuid issue is more pressing.

**Comment by mokaddem** [comment]
@JakubOnderka I said **probably mitigate** because the OP of the issue mentioned in this comment https://github.com/MISP/MISP/issues/6034#issuecomment-664193893 that the UUID for attributes was duplicated, which will not be possible once this is merged. ;)

**Comment by JakubOnderka** [comment]
This is actually weird, because evens and attributes tables has unique index for uuid row:

```sql
CREATE TABLE IF NOT EXISTS `attributes` (
...
  `uuid` varchar(40) COLLATE utf8_bin NOT NULL,
...
  UNIQUE INDEX `uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

And it is there since 2015 (version 2.3.115) (see https://github.com/MISP/MISP/commit/556688069a83298184444cca0541d2a5a643df40).

So this should be redundant: 

https://github.com/MISP/MISP/pull/6168/files#diff-e97ea4c940ab8c923d78ae2b7e81a809R1485-R1489

Or am I wrong?

**Comment by iglocska** [comment]
OK, then I wasn't crazy. I remembered adding the constraint a long long time ago. We indeed have it because of a very old MISP that was updated release after release - must have missed this somehow.

**Comment by sustefil** [comment]
Hi guys, 

regarding the issue with duplicated UUIDS:

https://github.com/MISP/MISP/issues/6034#issuecomment-664193893

In our tables, the UUID is NOT unique, which is really weird (because as you mentioned, it's in the install script). If I dump the table, I get this:

```
CREATE TABLE `attributes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `event_id` int(11) NOT NULL,
  `object_id` int(11) NOT NULL DEFAULT '0',
  `object_relation` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `category` varchar(255) COLLATE utf8_bin NOT NULL,
  `type` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `value1` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `value2` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `to_ids` tinyint(1) NOT NULL DEFAULT '1',
  `uuid` varchar(40) COLLATE utf8_bin NOT NULL,
  `timestamp` int(11) NOT NULL DEFAULT '0',
  `distribution` tinyint(4) NOT NULL DEFAULT '0',
  `sharing_group_id` int(11) NOT NULL,
  `comment` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `disable_correlation` tinyint(1) NOT NULL DEFAULT '0',
  `first_seen` bigint(20) DEFAULT NULL,
  `last_seen` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `uuid` (`uuid`),
  KEY `event_id` (`event_id`),
  KEY `sharing_group_id` (`sharing_group_id`),
  KEY `type` (`type`),
  KEY `category` (`category`),
  KEY `value1` (`value1`(255)),
  KEY `value2` (`value2`(255)),
  KEY `object_id` (`object_id`),
  KEY `object_relation` (`object_relation`),
  KEY `deleted` (`deleted`),
  KEY `first_seen` (`first_seen`),
  KEY `last_seen` (`last_seen`)
) ENGINE=InnoDB AUTO_INCREMENT=505728 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

```


I can then successfully insert an attribute with the same UUID like this:

```
MariaDB [misp]> insert into attributes (uuid) values("test_uuid");
Query OK, 1 row affected, 6 warnings (0.00 sec)

MariaDB [misp]> select * from attributes order by id desc limit 2;
+--------+----------+-----------+-----------------+----------+------+--------+--------+--------+-----------+-----------+--------------+------------------+---------+---------+---------------------+------------+-----------+
| id     | event_id | object_id | object_relation | category | type | value1 | value2 | to_ids | uuid      | timestamp | distribution | sharing_group_id | comment | deleted | disable_correlation | first_seen | last_seen |
+--------+----------+-----------+-----------------+----------+------+--------+--------+--------+-----------+-----------+--------------+------------------+---------+---------+---------------------+------------+-----------+
| 507060 |        0 |         0 | NULL            |          |      |        |        |      1 | test_uuid |         0 |            0 |                0 | NULL    |       0 |                   0 |       NULL |      NULL |
| 507059 |        0 |         0 | NULL            |          |      |        |        |      1 | test_uuid |         0 |            0 |                0 | NULL    |       0 |                   0 |       NULL |      NULL |
+--------+----------+-----------+-----------------+----------+------+--------+--------+--------+-----------+-----------+--------------+------------------+---------+---------+---------------------+------------+-----------+
2 rows in set (0.00 sec)

```

Any thoughts? We can review our install procedure and used scripts, but I believe we install it normally.

Thanks

**Pull request merged**
