### PR TITLE
MISP ansible

### PR DESCRIPTION
**Pull request by deloittem**
## MISP - Ansible installation script
- V0.1
  - Nginx support only
  - Backup script provided
## Instructions
- From the ansible repository, run the following command:

``` bash
ansible-playbook -i <host>, misp.yml -K -u <user>
```
- Update the self-signed certificate in /etc/nginx/ssl
- Create and export your GPG key:

``` bash
sudo -u www-data gpg --homedir /opt/misp-server/misp/.gnupg --gen-key
sudo -u www-data gpg --homedir /opt/misp-server/misp/.gnupg --export --armor YOUR-EMAIL > /opt/misp-server/misp/app/webroot/gpg.asc
```
- Login with:
  - user: admin@admin.test
  - password: admin
    and update the admin password
- Configure MISP in administration panel, server settings
## Notes
- the user must have admin rights
- a self-signed certificate is generated to allow you to test the installation
- installation directory is: /opt/misp-server/misp
- backup directory is: /opt/misp-server/backup
## Backup script

If enabled, a backup script create each day a new archive with a MySQL misp database dump and misp files to allow easy restore.
- these archives are created in: /opt/misp-server/backup
- a script to easy restore MISP from an archive is provided in the same directory
- to use the restore script, login as misp user and run the following command:

``` bash
./misp_restore <archive_timestamp>.tar.gz
```

### CODE REVIEW

**Comment by adulau** [comment]
Thank you very much for the contribution. This is very nifty.

**Comment by iglocska** [comment]
Excellent, thanks a lot!

**Comment by Rafiot** [comment]
I'll create a dedicated repository for ansible so we can do clean runs in Travis and upload everything on the galaxies. 

Note that I have n idea what I'm talking about but this like looks cool: http://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github

**Comment by juju4** [comment]
Some discussions would be nice to re-align as there are multiple initiatives and ideally could combine.
There are 3 ansibles roles under review at least
- https://github.com/MISP/MISP/pull/1413 + https://github.com/MISP/ansible (3 roles: misp, mysql, nginx. nginx only, backup/restore scripts, apt-based)
- https://github.com/MISP/MISP/pull/1495 (one role with apache2/modsecurity, trusty and xenial)
- https://github.com/MISP/MISP/issues/1103 (one role with dependencies on redhat-epel, on xenial, trusty and centos7) aka https://github.com/juju4/ansible-MISP

last one (mine) already includes testing with travis/github, kitchen/lxd and kitchen/vagrant/virtualbox and also a packer profile (to generate image for vbox/vmware/digitalocean, probably easy to extend to aws or else). validation is done with serverspec for now at a basic level (https://github.com/juju4/ansible-MISP/tree/master/test/integration/default/serverspec) and possible extension in future (subject of ticket https://github.com/MISP/MISP/issues/1103)
Why so many? started with vagrant and after kitchen/vagrant, next travis and last lxd. In my experience, they all have different view that can be useful. Sadly current usage of lxd inside travis is not working very well so sticking with a simple execution or docker there.

I would also suggest to keep role in a different repository as testing in my view would focus more on deployment/monitoring that unit/app testing. It should be done per role as I believe galaxy is not taking multiples in a row.
As for apache/nginx/modsecurity/https, while it's good to have sane secure default, you can't expect architecture to be the same everywhere so it should be possible to disable them (or to set them in a different role like modsecurity. In my case, I have https://github.com/juju4/ansible-harden-webserver/)

**Pull request merged**
