### PR TITLE
add some X509 new type

### PR DESCRIPTION
**Pull request by truckydev**
add type : 

    x509-fingerprint-MD5
    x509-fingerprint-SHA256
    x509-issuer

#### What does it do?

https://github.com/MISP/MISP/issues/2356

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by truckydev** [comment]
As recommanded in https://github.com/MISP/MISP/issues/2356, I have add 

- x509-subject
- x509-validity

I don't add other because I don't it's very useful.

From the rfc, just specify value in the "x508-validity" field. (https://www.ietf.org/rfc/rfc5280.txt)

> Validity ::= SEQUENCE {
>         notBefore      Time,
>         notAfter       Time }

- x509-not-before
- x509-not-after

**Comment by adulau** [comment]
Thanks for bringing this up. Could you review the current x509 MISP template?

https://github.com/MISP/misp-objects/blob/master/objects/x509/definition.json

and see if everything is there.

**Comment by StefanKelm** [comment]
Looks good to me; just a small typo: "pubkey-info-seize" should read "pubkey-info-size".

**Comment by adulau** [comment]
@StefanKelm  Just fixed the typo https://github.com/MISP/misp-objects/commit/08e5ebe9954b5ad98171f9a7eed9958380aa0669 Thank you.

**Comment by truckydev** [comment]
I don't see this 3 types in x509 misp-object.

You need a PR ?

**Comment by truckydev** [comment]
I think you can close here after https://github.com/MISP/misp-objects/pull/18 :)

**Comment by truckydev** [comment]
https://github.com/MISP/misp-objects/commit/7ef22421391a3edbe3fbdb9f43c51eaa1c923576

**Pull request closed without merging**
