### PR TITLE
Braces

### PR DESCRIPTION
**Pull request by rotanid**
this PR aims to achieve a consistent coding convention regarding spaces/brackets.
it applies the way it was already done in most parts of the code to the other parts.

commands:

```
# add space before opening curly brackets
egrep -rlI "\){( |/|$)" | grep "\.php" | while read file; do sed -i -r 's|\)\{( .*\|/.*)?$|) {\1|g' $file; done
# add space after keywords if/for/foreach/while/switch/catch
egrep -rlI "\s(if|for|foreach|while|switch|catch)\(" | egrep "\.(php|ctp)" | while read file; do sed -i -r 's|(\s+)(if\|for\|foreach\|while\|switch\|catch)\(|\1\2 (|g' $file; done
# remove space after unset before opening brace
grep -rlI "unset (" | while read file; do sed -i "s|unset (|unset(|" $file; done
# use consistent spacing around else/elseif
egrep -rlI "} ?else{" | egrep "\.(php|ctp)" | while read file; do sed -i -r "s|\} ?else\{|} else {|" $file; done
egrep -rlI "\selseif \(" | egrep "\.(php|ctp)" | while read file; do sed -i -r "s|(\s+)elseif \(|\1else if (|" $file; done
```

### CODE REVIEW

**Comment by iglocska** [comment]
This one will most likely cause issues. Could you revert the elseif -> else if changes? Both are valid but splitting it into two words prevents the use of the if alternate syntax, which we use in the views frequently.

**Comment by rotanid** [comment]
you didn't have to close the PR for this, i can always update it using rebase and force push :-)
i did that now, i think you meant the changes in global_menu.ctp and side_menu.ctp which i have reverted now.
if github allows, please reopen this PR so we don't need a new one.

**Comment by Rafiot** [comment]
For some reason, I cannot reopen either: it says the branch has been force pushed or recreated, I don't really get why that would be a problem, but github isn't happy. 
Can you open an other PR, please?

**Comment by iglocska** [comment]
Argh indeed. That is weird, sorry about that.

**Comment by rotanid** [comment]
weird behaviour, so i would have had to wait for you to reopen and then push my changes...
new PR follows.

**Pull request closed without merging**
