### PR TITLE
Much faster IPv4 warninglists

### PR DESCRIPTION
**Pull request by JakubOnderka**
Reworked version of pull request https://github.com/MISP/MISP/pull/4965, that also fixed bug https://github.com/MISP/MISP/issues/5008. 

Benchmark: 
* Event with 788 IPv4 and IPv6 addresses 
* Enabled 'Specialized list of IPv4 addresses belonging to common VPN providers and datacenters' and 'Specialized list of IPv6 addresses belonging to common VPN providers and datacenters' warninglists.
* Measured loading time of the whole page with event
* Before this PR: 17 006 ms
* **After this PR: 1 413 ms**

Tested on production instance, but because it is big change, I can write testcase if you want.

### CODE REVIEW

**Comment by JakubOnderka** [comment]
Please do not merge now, I found much faster way how to compare IPv4 CIDRs. I will push to this branch new commit soon.

**Comment by iglocska** [comment]
OK, thanks a lot, was close ;)

**Comment by JakubOnderka** [comment]
@iglocska Updated and ready to merge!

**Comment by iglocska** [comment]
Thanks a lot!

**Pull request merged**
