### PR TITLE
chg: improve fopen/fread/fwrite handling via Lib

### PR DESCRIPTION
**Pull request by rotanid**
introduces better (if there even was any) error handling to fopen/fread/fwrite.

using a separate private function in two of the three files to reduce code redundancy.

### CODE REVIEW

**Comment by rotanid** [comment]
wait with the merge, i'll try to move the functions to a Lib so they can be re-used

**Comment by rotanid** [comment]
i updated this PR, it now uses an external Lib so the functions can be re-used.

as that is my first try at generating a Lib for cakephp, there might be problems with the way i did it.
for example, i was not sure if there are Exceptions allowed in a Lib, but it would have been more code if not (or the error messages would have been more general).

**Comment by iglocska** [comment]
Thanks a lot, working great and very clean!

**Comment by cristianbell** [comment]
great work, thanks!

**Pull request merged**
