### PR TITLE
Add SMIME encryption & signing -- Update MISP 2.4

### PR DESCRIPTION
**Pull request by devnull-**
Hello all,

I finally updated the old pull request [306](https://github.com/MISP/MISP/pull/306) (open since 1 year and half :smiley: ). This SMIME patch works with the latest MISP version (2.4.33). 

Don't hesitate to contact me if you need some help or if you have some question about the S/MIME patch.

I attached the original message of the pull request [306](https://github.com/MISP/MISP/pull/306) to add additional details. Don't hesitate review the small [instructions](https://github.com/MISP/MISP/commit/536adba5bbf4b55955ba6960e70963898a746179) regarding the installation of this patch.

-------------------------------------- original pull request 306 ----------------------------------------------------

Hello all,

The mission of this patch is to add the support of SMIME [1](https://en.wikipedia.org/wiki/S/MIME) in order to improve the solutions to encrypt & sign emails in MISP :)

This patch works when:
- SMIME enabled & GPG disabled: In this context, all emails will be sent encrypted and signed using S/MIME. If the user doesn't set a public certificate (for encipherment), he will receive an email (clear text) to invite him to connect to MISP in order to obtain the detail on the published event (the template for this email is attached to this "Pull request").
- GPG & SMIME enabled: By default, GPG is always preferred :). Thus, if the user sets a GPG key and a public certificate in this profile, he will receive all email encrypted & signed using GPG. If the user doesn't set a GPG key but has set a public certificate, the emails will be encrypted & signed using S/MIME. Of course, if no GPG key and public certificate are set, he will receive an email (clear text) to invite him to connect to MISP in order to obtain the detail on the published event (the template for this email is attached to this "Pull request").
- SMIME disabled: In this context, the email will be sent encrypted & signed using GPG, if GPG is enabled. If no GPG key is set in the user profile, the user will receive an email (clear text) to invite him to connect to MISP in order to obtain the detail on the published event (the template for this email is attached to this "Pull request"). 

The different steps to install this patch is defined the INSTALL.txt (section: ' 9/ SMIME patch')

At the moment, I currently use this patch (and it's working well) but this patch is still in the "beta phase" and don't blame me for bugs and dirty hacks in the code.

devnull-

[2]: At the moment, AES_256_CBC is used to encrypt the email

---

```
Hello, 

The event number 43 was published on the MISP platform. 

Since no GPG/PGP key or public certificate is set in your MISP profile, you can not directly receive the information in an encrypted email. 
You can fill out you profile with your GPG/PGP key or public to receive encrypted email. 

To access to the event involved, please click on the following link:
URL    : https://misp.xxx.xxx.com/events/view/43


Best regards,

XXXXXX  xxxx

```

---

-------------------------------------- original pull request  306 ----------------------------------------------------

### CODE REVIEW

**Comment by Rafiot** [comment]
wohoo, thank you very much! :) 

I didn't try anything and don't have an environment I can easily give a try but I have the following questions:
- if we merge it right now, do the admin need to do anything do use MISP the way they used the platform before (does it break anything?)
- Is SMIME disabled by default?

**Comment by devnull-** [comment]
Hello @Rafiot 

> wohoo, thank you very much! :)

You're welcome :)

> I didn't try anything and don't have an environment I can easily give a try but I have the following questions:
> 
>    if we merge it right now, do the admin need to do anything do use MISP the way they used the platform before (does it break anything?)

Not at all :) By default, the SMIME patch uses GPG encryption if a GPG key is set in MISP profile. If not, it tries to use SMIME if an encryption certificate is set. 

>    Is SMIME disabled by default?

Yes. To enable SMIME, you have to modify the SMIME parameters in your config.php -- https://github.com/MISP/MISP/pull/1057/commits/26036ea3fa19f30693873cb4fd70cef2c7205b0b

```
  'SMIME' => 
  array (
    'onlyencrypted' => false,
    'email' => 'email@address.com',
    'cert_public_sign' => '/var/www/MISP/.smime/email@address.com.pem',
    'key_sign' => '/var/www/MISP/.smime/email@address.com.key',
    'password' => 'XXXXXXXXXXXXXXXXXXXXXX',
    ),
```

**Comment by elhoim** [comment]
Cool work!

Will the SMIME "feature switch" also show up on the settings page?

**Comment by jaegeral** [comment]
what needs to be done to get this merged? I know some people would love to see that feature.

Do you need tests? Or solving the conflicts?

**Comment by iglocska** [comment]
Almost there, I am doing some changes to it and will try to push it asap. You can track the progress on feature/smime.

Thanks a lot for all the work @devnull-

**Comment by devnull-** [comment]
You're welcome @iglocska :)

Don't hesitate to contact me if you need some help or if you have some question about the S/MIME patch.

**Comment by iglocska** [comment]
Will do, I think it's pretty much good to go for the merge, will run some
more tests and merge it tomorrow. Thanks again!

**Comment by iglocska** [comment]
It is now merged, thanks again!

**Pull request merged**
