### PR TITLE
new: Add tests after install

### PR DESCRIPTION
**Pull request by Rafiot**
I'm currently testing that, and I'm unsure if it is the right place to run the tests, but in theory, the goal at the end of that is to discard every VM that doesn't pass the tests.

### CODE REVIEW

**Comment by Rafiot** [comment]
Confirmed working on a fresh Ubuntu 18.04 install.

**Comment by iglocska** [comment]
Awesome, thanks!

**Comment by Rafiot** [comment]
weeeeel, not sure that should be merged... The script I modified is autogenerated, and I'm not sure how that works. @SteveClement: can you look at it before we forget about it?

**Comment by iglocska** [comment]
oh woops. Sorry.

**Pull request merged**
