### PR TITLE
chg: Update hover UI

### PR DESCRIPTION
**Pull request by wesleya**
Offers bug fixes and UI improvements to make attribute hovers and popups more useful. Proposes a new hover layout with attributes grouped by module name for a cleaner, more compact UI, especially when multiple modules are enabled at the same time.

#### What does it do?

* add some logic to choose better hover placement
* make hover hide on outside click, to allow using the scrollbar to view full hover
* add an icon in the hover tooltip to turn it into a popup
* move popup close button to better position
* group attributes for each module in hover UI
* prevent duplicate enrichment api queries once the first one is done

#### Questions

- [ ] Does it require a DB change?
- [ ] Are you using it in production?
- [ ] Does it require a change in the API (PyMISP for example)?

#### Release Type:
- [ ] Major
- [ ] Minor
- [X] Patch

### CODE REVIEW

**Comment by adulau** [comment]
This pull request **introduces 1 alert** when merging 8b9436d3fe8fff3dfec0fecdc1fcacd3bae92c1e into 98cb4e63d419d9fd6811ae214f67c977c8c40903 - [view on LGTM.com](https://lgtm.com/projects/g/MISP/MISP/rev/pr-991d613eaeda5ca070f94b5868fc41ff91c9cdc7)

**new alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adulau** [comment]
This pull request **introduces 1 alert** when merging a33b5f6e6574161c4221ece04591c788b49017f3 into 98cb4e63d419d9fd6811ae214f67c977c8c40903 - [view on LGTM.com](https://lgtm.com/projects/g/MISP/MISP/rev/pr-a2fe1d661b1e7067a522a7d0da17823bdadcd441)

**new alerts:**

* 1 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adulau** [comment]
Thank you very much. I'll do some testing.

**Comment by adulau** [comment]
Thank you very much for your contribution. It's indeed a significant improvement. Don't hesitate if you see any other issues.

**Comment by wesleya** [comment]
Awesome thank you for the quick reply!

**Pull request merged**
