### PR TITLE
Create cake_dev.pot for FR_fr

### PR DESCRIPTION
**Pull request by truckydev**
fr for cake_dev.po
#### Release Type:
- [ ] Major
- [X] Minor
- [] Patch

### CODE REVIEW

**Comment by iglocska** [comment]
Looks like the main po file was left off, could you attach that too? Thanks ;-)

**Comment by truckydev** [comment]
there was no original po file. in fra directory.
this one is a copy/past from https://github.com/MISP/MISP/blob/2.4/app/Locale/cake_dev.pot

**Comment by adulau** [comment]
Feel free to update the translation. When you have around close to 100% of the translation, we will merge it. Thank you very much!

**Comment by SteveClement** [comment]
@truckydev @cvandeplas what is the status?
I will import the PO file from Feature_French to Crowdin to have an idea how far along we are.

Here is the [Crowdin Project](https://crowdin.com/project/misp)

**Pull request merged**
