### PR TITLE
Azure Active Directory Authentication

### LINKED ISSUE #6641: Azure AD integration, stuck with [CakeException] Authentication adapter "AADAuthenticate" error
Hi,

Based on the code snippet from https://www.sipponen.com/archives/4024 I'd like to setup Azure Active Directory integration for authentication. The code seems to work properly, and you can query the AD-groups. This allows to have MISP access defined by AD groups.

Now, the hurdle is how to integrate this into MISP. As far as I can check, the customauth module isn't possible because I can't instruct AAD to include a custom header. LDAP auth is also not possible because that doesn't work with AAD.

1) In config.php in the array Security I added 
`'auth'=>array('AADAuth.AADAuthenticate')`
and included a dummy section to set configuration variables.

```
	'AADAuthenticate'  =>                      
  array(
    'test'         => 'REMOTE_USER',       
  ),
```

2) In bootstrap I added 
`CakePlugin::load('AADAuth');`

3) In MISP/app/Plugin/AADAuth/Controller/Component/Auth/AADAuthenticate.php I created a class
`	class AADAuthenticate extends BaseAuthenticate {`

Unfortunately this keeps throwing the error message "Authentication adapter "AADAuthenticate" was not found.".

```
2020-11-24 11:49:49 Error: [CakeException] Authentication adapter "AADAuthenticate" was not found.
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(695): AuthComponent->constructAuthenticate()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_getUser()
#2 /var/www/MISP/app/Controller/AppController.php(1175): AuthComponent->startup(Object(UsersController))
#3 /var/www/MISP/app/Controller/AppController.php(294): AppController->_loadAuthenticationPlugins()
#4 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
```

Do you have any suggestions where to look first? Feels like "close" ;-)

### PR DESCRIPTION
**Pull request by cudeso**
#### What does it do?

Fixes #6641 
Adds Azure Active Directory authentication (first 'rough', but working version)

#### Questions

- [ ] Does it require a DB change? No
- [ ] Are you using it in production? Yes
- [ ] Does it require a change in the API (PyMISP for example)? No

### CODE REVIEW

**Comment by adulau** [comment]
That's a great contribution. Thanks a lot! We will do some review before merging as it's an authentication module.

**Comment by cudeso** [comment]
@adulau  sure thing. It works, but certainly room for improvement. Have mailed about it with @iglocska .
Once it's included I'll add a post to the website, with the Azure apps part and how to configure.

**Comment by ChuckSpeaks** [comment]
Was looking for this exact functionality. Using Azure AD for authentication in front of MISP. Interested to see if the Azure AD MFA will function as well.

**Comment by garrit-schroeder** [comment]
Is it possible to use this plugin for other general OAuth 2 Identity Providers? Like Keycloak?

**Comment by cudeso** [comment]
> Is it possible to use this plugin for other general OAuth 2 Identity Providers? Like Keycloak?

Don't know about other ID providers but in theory yes. I already included some configuration elements.
The **check_ad_groups** is very specific to AAD, so you should disable at least that option.

**Comment by legoguy1000** [comment]
> > Is it possible to use this plugin for other general OAuth 2 Identity Providers? Like Keycloak?
> 
> Don't know about other ID providers but in theory yes. I already included some configuration elements.
> The **check_ad_groups** is very specific to AAD, so you should disable at least that option.

You could change this PR to create a generic OpenID Connect Auth Plugin and as part of the configs, populate the different urls for user info, groups....

**Comment by cudeso** [comment]
> > > Is it possible to use this plugin for other general OAuth 2 Identity Providers? Like Keycloak?
> > 
> > 
> > Don't know about other ID providers but in theory yes. I already included some configuration elements.
> > The **check_ad_groups** is very specific to AAD, so you should disable at least that option.
> 
> You could change this PR to create a generic OpenID Connect Auth Plugin and as part of the configs, populate the different urls for user info, groups....

I'm not sure if OpenID has the similar concept or approach for groups (ie. the "v1.0/me/memberOf" and then querying the results). As I don't have an OpenID access at hand and a use case to develop for it, this would be a bit out of scope of the initial idea. But developing a generic OpenID plugin would certainly make sense.

**Comment by legoguy1000** [comment]
> > > > Is it possible to use this plugin for other general OAuth 2 Identity Providers? Like Keycloak?
> > > 
> > > 
> > > Don't know about other ID providers but in theory yes. I already included some configuration elements.
> > > The **check_ad_groups** is very specific to AAD, so you should disable at least that option.
> > 
> > 
> > You could change this PR to create a generic OpenID Connect Auth Plugin and as part of the configs, populate the different urls for user info, groups....
> 
> I'm not sure if OpenID has the similar concept or approach for groups (ie. the "v1.0/me/memberOf" and then querying the results). As I don't have an OpenID access at hand and a use case to develop for it, this would be a bit out of scope of the initial idea. But developing a generic OpenID plugin would certainly make sense.

You are correct.  I would say to make this as extensible as possible, you could split this up.  make a generic OpeinID connect authentication plugin and then extend that for the AAD plugin where u can add the extra custom functions. That way every other OpenID connect based IDP can be used or have a custom plugin extended from that. Just thoughts on how to get the best of both worlds.

**Comment by garrit-schroeder** [comment]
> > > > > Is it possible to use this plugin for other general OAuth 2 Identity Providers? Like Keycloak?
> > > > 
> > > > 
> > > > Don't know about other ID providers but in theory yes. I already included some configuration elements.
> > > > The **check_ad_groups** is very specific to AAD, so you should disable at least that option.
> > > 
> > > 
> > > You could change this PR to create a generic OpenID Connect Auth Plugin and as part of the configs, populate the different urls for user info, groups....
> > 
> > 
> > I'm not sure if OpenID has the similar concept or approach for groups (ie. the "v1.0/me/memberOf" and then querying the results). As I don't have an OpenID access at hand and a use case to develop for it, this would be a bit out of scope of the initial idea. But developing a generic OpenID plugin would certainly make sense.
> 
> You are correct. I would say to make this as extensible as possible, you could split this up. make a generic OpeinID connect authentication plugin and then extend that for the AAD plugin where u can add the extra custom functions. That way every other OpenID connect based IDP can be used or have a custom plugin extended from that. Just thoughts on how to get the best of both worlds.

In OpenId you can map user groups and roles into the tokens and then on SP Level check these groups and roles. Pretty straight forward to be honest.

**Comment by cudeso** [comment]
Hello @iglocska would you be able to have a look at this PR and if something needs to be changed? The suggestion to extend it to OpenID is certainly good but was/is not in the intended use case.

**Comment by garrit-schroeder** [comment]
I have now created a pull request using a default implementation of oauth2 / open id connect.

https://github.com/MISP/MISP/pull/7064

We might actually be able combine these two pull requests because they are mostly similar.

**Comment by iglocska** [comment]
Thanks a lot, indeed, it looks very clean. I have no way of testing the module currently, but it is cleanly inert by default and thus poses no risk, so merged pre-emptively. 

@garrit-schroeder - doing the same with your PR and we can combine the two indeed in the future.

**Comment by iglocska** [comment]
And just as I write that I read the comments in the other PR... :)

**Comment by sdzhangtao** [comment]
This module looks very good, however I was stuck on an issue following the Azure AD integration. The https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token was requested three times, the first time access token was granted. 2nd and 3rd time received error
2021-03-07 04:13:06 Warning: {"error":"invalid_grant","error_description":"AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\r\nTrace ID: 87996aab-255e-45dc-9ecd-8306c2e81100\r\nCorrelation ID: cfa6bccb-ef8f-4c7f-a29c-9a5c5e07027d\r\nTimestamp: 2021-03-07 04:13:07Z","error_codes":[54005],"timestamp":"2021-03-07 04:13:07Z","trace_id":"87996aab-255e-45dc-9ecd-8306c2e81100","correlation_id":"cfa6bccb-ef8f-4c7f-a29c-9a5c5e07027d"}
I created a bug report as well.
https://github.com/MISP/MISP/issues/7169

**Pull request merged**
