### PR TITLE
Changes to upload of malware-sample in order to also create attributes

### PR DESCRIPTION
**Pull request by stevengoossensB**
Changes to upload of malware-sample in order to also create attributes of the type MD5,SHA1 and SHA256

### CODE REVIEW

**Comment by Rafiot** [comment]
Thanks for the pull request.

I'm not sure why you want to do that? The correlation is already working if there is a match on the filename OR on the hash. Adding extra attributes for the hashes without filenames will add noise.

Or do you have a specific usecase? such as exporting hashes and you miss the md5 if they come from a malware-sample?

**Comment by stevengoossensB** [comment]
Hi Raphael,

The main reason is that all our integration works on the export of MD5 hashes (the md5 type). If I run the MD5 export, it doesn’t include the hashes attached to the 'filename|MD5’. It is true though that I could’ve changed the export scripts to include an export for filename|MD5, our the MISP project could include them in the export for the MD5 attribute type..

This however shouldn’t add ‘noise’ to the monitoring, as the hash is exactly the same and malicious, but will indeed fill up the database more. 

Best regards,

Steven

**Comment by iglocska** [comment]
Hello Steven,

would using the /hids APIs be a solution to you? You can also specify MD5 there and it will fetch the hashes from all attributes with md5 hashes in them (md5, filename|md5, malware-sample).

Best regards,
Andras

**Comment by stevengoossensB** [comment]
Hi Andras,

That would do the trick. 

Best regards,

Steven

**Comment by elhoim** [comment]
@stevengoossensB OK if I close the PR?

**Comment by stevengoossensB** [comment]
Yes, no problem.

**Comment by Rafiot** [comment]
Thanks!

**Pull request closed without merging**
